### ISSUE TITLE
After deploying on production getting error on MVC Report viewer

### ISSUE THREAD

**Issue by gunjanhshah** [ilich/MvcReportViewer#105]
Hi,

        This code works fine on development machine but it crashes on the web server with this error:

CS1705: Assembly 'MvcReportViewer, Version=0.7.5618.16305, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

please help.

**Comment by eflorespalma** [comment]
You have to install this in your web server http://www.microsoft.com/en-us/download/details.aspx?id=35747

**Comment by gunjanhshah** [comment]
Thanks a lot for your reply.

On Thu, Jul 23, 2015 at 2:44 PM, eflorespalma <notifications@github.com>
wrote:

> You have to install this in your web server
> http://www.microsoft.com/en-us/download/details.aspx?id=35747
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ilich/MvcReportViewer/issues/105#issuecomment-124206870>
> .
>



-- 
Thanks,

Gunjan Shah

**Comment by gunjanhshah** [comment]
It worked.

On Thu, Jul 23, 2015 at 2:45 PM, Gunjan Shah <gunjanhshah@gmail.com> wrote:

> Thanks a lot for your reply.
>
> On Thu, Jul 23, 2015 at 2:44 PM, eflorespalma <notifications@github.com>
> wrote:
>
>> You have to install this in your web server
>> http://www.microsoft.com/en-us/download/details.aspx?id=35747
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ilich/MvcReportViewer/issues/105#issuecomment-124206870>
>> .
>>
>
>
>
> --
> Thanks,
>
> Gunjan Shah
>



-- 
Thanks,

Gunjan Shah

**Comment by morales-franco** [comment]
Hi!
LocalHost worked perfect, but after deploy: this is the error:

The Report Viewer Web Control HTTP Handler has not been registered in the application's web.config file. Add <add verb="*" path="Reserved.ReportViewerWebControl.axd" type = "Microsoft.Reporting.WebForms.HttpHandler, Microsoft.ReportViewer.WebForms, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" /> to the system.web/httpHandlers section of the web.config file, or add <add name="ReportViewerWebControlHandler" preCondition="integratedMode" verb="*" path="Reserved.ReportViewerWebControl.axd" type="Microsoft.Reporting.WebForms.HttpHandler, Microsoft.ReportViewer.WebForms, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" /> to the system.webServer/handlers section for Internet Information Services 7 or later.


In my webConfig:
<httpHandlers>
      <add path="Reserved.ReportViewerWebControl.axd" verb="*" type="Microsoft.Reporting.WebForms.HttpHandler, Microsoft.ReportViewer.WebForms, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" validate="false" />
    </httpHandlers>

<system.webServer>
    <handlers>
            <add name="ReportViewerWebControlHandler" preCondition="integratedMode" verb="*" path="Reserved.ReportViewerWebControl.axd" type="Microsoft.Reporting.WebForms.HttpHandler, Microsoft.ReportViewer.WebForms, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" />
      <remove name="ReportViewerWebControlHandler" />
    </handlers>


please help me!

**Comment by ilich** [comment]
I'd probably try to remove system.WebServer handler first and test it. If it still does not work then remove the httpHandler and restore the webServer handler. If it still does not work then create sample asp.net web forms application and test report viewer there. After that you can compare web.config files.

**Comment by morales-franco** [comment]
Thanks, It works! But the view show a IFRAME Empty.
I have a Local report 
App_data --> Reports --> EmptyReport.rdlc (embedded resource)
This report only has a text.

Code View:
@Html.MvcReportViewerFluent("App_Data/Reports/NoDataReport.rdlc").ProcessingMode(ProcessingMode.Local).Attributes(new { Height = 900, Width = "100%", style = "border: none; background-color:white;" })

LocalHost is working but when I deployed, the view show a IFRAME EMPTY.

WebConfig
< add key="MvcReportViewer.AspxViewer" value="~/MvcReportViewer.aspx" />
< add key="MvcReportViewer.AspxViewerJavaScript" value="~/Scripts/MvcReportViewer.js" />
< add key="MvcReportViewer.ErrorPage" value="~/MvcReportViewerErrorPage.html" />
< add key="MvcReportViewer.ShowErrorPage" value="false" />
< add key="MvcReportViewer.ReportServerUrl" value="" /> 
< add key="MvcReportViewer.Username" value="" />
< add key="MvcReportViewer.Password" value="" />
< add key="MvcReportViewer.EncryptParameters" value="False" />
< add key="MvcReportViewer.IsAzureSSRS" value="False" />
< add key="MvcReportViewer.LocalDataSourceProvider" value="MvcReportViewer.SessionLocalDataSourceProvider, MvcReportViewer" />
Help me please!
