### ISSUE TITLE
Microsoft.ReportingServices.Diagnostics.Utilities.ReportParameterTypeMismatchException

### ISSUE THREAD

**Issue by cburgessiasset** [ilich/MvcReportViewer#107]
Hi,

I'm getting the above exception when trying to pass in a multi valued integer to a report parameter. What data format should I be using for this? I've tried List&lt;int&gt;, List&lt;string&gt;, int[] and comma delimited string.

**Comment by cburgessiasset** [comment]
I've also tried using a Microsoft.Reporting.WebForms.ReportParameter, no luck.

**Comment by ilich** [comment]
I have updated the ReportParameter sample to pass int[]. But there is a problem with passing int[] using anonymous types. I am going to fix it soon and deploy new NuGet package.

**Comment by ilich** [comment]
The issue has been fixed. It will be deployed in v 0.7.1 later today or tomorrow.

**Comment by ilich** [comment]
Please make sure you use VS2015 to build the project from the source code.

**Comment by cburgessiasset** [comment]
Thanks Ilich, that worked. I'm not using VS2015, so I just left out the syntax changes that require it.
