### ISSUE TITLE
Subreport implementation

### ISSUE THREAD

**Issue by ecosme8** [ilich/MvcReportViewer#109]
Hello,

First of allI want to tell you that you have done an awesome job. The reason I'm creating this issue it's because I haven't found a way to use a Subreport with a value from the Main report.

I have loaded the Main report with no problems, and the data is being shown, but the subreport displays the following message:

Data retrieval failed for the subreport, 'Subreport', located at: C:\Repositories\ReportApp\ReportApp\App_Data\Reports\Subreport.rdlc. Please check the log files for more information.

Is there anyway you can provide an example using a Report with a subreport?

Would like to hear from you soon, thanks.

**Comment by ilich** [comment]
I have no experience with subreports. Could you send me an ASP.NET Web Forms example/article which uses subreports. I will try to add its support to the future release.

**Comment by ecosme8** [comment]
Thank you for your fast answer,

Here's a good example on what I want to achieve: https://www.youtube.com/watch?v=P9O77qT_KGI

A Main report passing a parameter value to the Subreport and the subreport shows the data based on that parameter value.

**Comment by VMirMK** [comment]
Is this resolved? i am getting this error: "Error: Subreport could not be shown."

How can I add a subreport and handle SubreportProcessingEventHandler?

**Comment by ilich** [comment]
Not yet. I do not have time now to implement big changes for the project. I hope to have it done by December this year.

**Comment by angelocarlotto** [comment]
Waiting for this feature.

**Comment by ilich** [comment]
Going live in 0.8
