### ISSUE TITLE
Poor performance with large datasets

### ISSUE THREAD

**Issue by cburgessiasset** [ilich/MvcReportViewer#110]
Hi again,

I just wanted to let you know about this one, in case you know of anything that will help me to resolve this issue. I am getting very slow performance with embedded datasets that return a large number of rows i.e. in the order of 5 digits. The reports are running locally. As far as I have worked out so far stepping through my code, the delay is occurring within the reportviewer control itself. Is this an issue that you have come across? Or tested for? Any ideas?

**Comment by cburgessiasset** [comment]
BTW, I implemented my own localreportdatasourceprovider class, which just uses a static Dictionary variable to store the datasets, so not storing in session. Our session state mode is SQLServer, and with large data sets, I was getting out of memory exceptions after just a few runs of the report. I'm getting slow performance with either datasourceprovider class though, just no exception if I store it in memory.

**Comment by ilich** [comment]
I have released MvcReportViewer 0.7.1 which has new local datasource provider which stores SQL queries instead of the data. https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewer/SqlLocalDataSourceProvider.cs  I think it will help to improve performance little bit.

Personally I'd try to switch from local reports to SSRS if it was possible.

**Comment by cburgessiasset** [comment]
Thanks Ilich. That is an improvement.

We however need to run in local mode (we have our own security model that needs to be applied). Having explored this further, I realise that the reportviewer control itself is adding the data sets to session state when in local mode, which can't be avoided as far as I can tell.

**Comment by ilich** [comment]
You replace the reports to plain HTML format for the preview and added a feature to download them as PDF generated using iTextSharp. I think this solution will improve your performance a lot.

**Comment by cburgessiasset** [comment]
Thanks for your suggestion, but I don't think I quite understand. Does the report viewer control have a configuration option to render as plain HTML? I haven't been able to find such an option.

**Comment by ilich** [comment]
No. I think it does not. My recommendation was to rewrite the system completely to avoid using Report Viewer control at all. It will take time, but you will have better performance at the end.

You can also try Telerik Reporting. I haven't used it myself, but I have heard good feedback about this product.

http://www.telerik.com/products/reporting.aspx
