### ISSUE TITLE
Question : passing dynamic parameters

### ISSUE THREAD

**Issue by JLR-UK** [ilich/MvcReportViewer#111]
Firstly, this is a great project, thanks for all your hard work.

Also, I'm new to git hub, so apologies in advance if I should be asking this somewhere else!

I *really* would like to build and pass a list of dynamic parameters to my reports where I pass string literals for BOTH the parameter name and the value to my controller\action.

I can't figure it out and have tried numerous methods and been googling for hours :-(

so I if had 

string p1 = "SupplierID";
string p1_val = "121";

How can I create a valid param object and pass it in to the code below replacing 

new {SupplierID=1, ClientID=121}

var rpt = this.Report(0, "Path", _host, _user, _pass, new {SupplierID=1, ClientID=121});

TIA for any help!

**Comment by ilich** [comment]
You can pass parameters as List<KeyValuePair<string, object>>() object. Please check https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/Multiple.cshtml example. I think it solves your problem.

**Comment by JLR-UK** [comment]
Hi IIya,

This isn't working for me.

I'm getting a similar error message as per my other various attempts.

Example code;

        public ActionResult Get_Report_From_SRSS(SRSS_Filters Model)
        {
            string _SRSS_Host_Name =
WebConfigurationManager.AppSettings["SRSS:Server"].ToString();
            string _SRSS_User =
WebConfigurationManager.AppSettings["SRSS:User"].ToString();
            string _SRSS_Password =
WebConfigurationManager.AppSettings["SRSS:Password"].ToString();
            MvcReportViewer.ReportFormat _Format =
(MvcReportViewer.ReportFormat)Model.Format;

            //example parameters - would normally be passed in the
model when I get this working
            var parameters = new List<KeyValuePair<string, object>>(){
                new KeyValuePair<string, object>("SupplierID", 1),
                new KeyValuePair<string, object>("ClientID", 121)
            };

            var rpt = this.Report(_Format, Model.Path + Model.Name,
_SRSS_Host_Name, _SRSS_User, _SRSS_Password, parameters);
            rpt.FileDownloadName = Model.DownloadFileName;
            return rpt;
        }

Returns

Server Error in '/' Application.
________________________________

Parameter 'Capacity' does not exist on this report

Description: An unhandled exception occurred during the execution of
the current web request. Please review the stack trace for more
information about the error and where it originated in the code.

Exception Details: System.ArgumentException: Parameter 'Capacity' does
not exist on this report


Any ideas?
