### ISSUE TITLE
How can I render rdl(not rdlc) files from my App_Data folder ?

### ISSUE THREAD

**Issue by vengi83644** [ilich/MvcReportViewer#113]
Can you please let me know how can I render local rdl files in my App_Data folder ?

* Do you have support for this ?
* If so, how will it have support for Shared Data sources ?

I am interested in having a custom report server and bring my rdl files from that server to this report viewer.

Thanks

**Comment by ilich** [comment]
No, you cannot render RDL report locally. You will have to install SSRS and deploy your reports there. You can use SQL Server Express with Advanced Services as a starting point.

**Comment by gitsubash** [comment]
Why can't I render RDL report locally if RDLC is possible? I am not clear about this argument as all the internet posts say that both file are same except RDLC we need to provide dataset and db related info ourself whereas in rdl files those are inside the xml element <Datasets>
So, wouldn't be it possible to just ignore that <dataset> element part and process the rdl files as like the rdlc one. But yes we can't see that .rdl file in VS designer mode, which i think should not affect the process.

Hi ilich, please clarify me and help me out as i need to deploy the SSRS generated rdl files into my mvc project (where i am using your mvcreportviewer html helper dll to achieve the requirement)
