### ISSUE TITLE
Custom configuration section in place of appSettings values?

### ISSUE THREAD

**Issue by tiesont** [ilich/MvcReportViewer#116]
I see that the MvcReportViewer current uses a large handful of appSettings key/value pairs to hold its configuration values. Would it make more sense to define a custom configuration section instead? For reference: http://haacked.com/archive/2007/03/12/custom-configuration-sections-in-3-easy-steps.aspx/

Basically, you would wind up with something like this (plus the bits to register the section):
```
<mvcReportViewer 
	webFormUrl="~/MvcReportViewer.aspx"
	scriptUrl="~/Scripts/MvcReportViewer.js"
	errorPage="~/MvcReportViewerErrorPage.html"
	showErrorPage="true"
	reportServerUrl="http://localhost/ReportServer_SQLEXPRESS"
	username=""
	password=""
	encryptParameters="false"
	isAzureSSRS="false"
	localDataSourceProvider="MvcReportViewer.SessionLocalDataSourceProvider, MvcReportViewer" />
```
Using a custom section like this has the distinct advantage of making it possible to force the values to be valid, since they get mapped to a custom reader that can be strongly typed.

If you're interested, I can build the required bits and submit a pull-request at some point.

**Comment by ilich** [comment]
This is good idea. You can start working on the change. Then I will merge it and add backward compatibility. Unfortunately we will have to keep supporting two versions to make sure that we will not break existing code.

**Comment by Lfwinster** [comment]
Hi, is it possible to set/override these settings in the code other than doing it in web.config, because sometimes eg. the reportServerUrl/username/password has to be programmatically changed based on bussiness logic.

**Comment by ilich** [comment]
Yes, you can pass username and password directly to Html.MvcReportViewer call. Please check the documentation in README.md file.

**Comment by Lfwinster** [comment]
Thanks, I saw that in the doc. One more dumb question, does this mean I can remove those keys in the web.config since I can pass through fluent API?

**Comment by ilich** [comment]
Yes, you can.
