### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by snusnu87** [ilich/MvcReportViewer#117]
Hi,

is it possible to set a different Language in the Report?
Ive tried to ovveride it by:
.ReportParameters(new { rs:ParameterLanguage="de-DE" })
He told me he couldnt find the Parameter.

Kind regards
SD

**Comment by ilich** [comment]
Hi,

I am not sure you can pass this to ASP.NET ReportViewer Control. At least my test report fails when I am trying to pass this parameter. 

I will implement support for SSRS rs:* parameters in the helper if you will send me an example how to pass them in Web Forms applications.

Sincerely,
Ilya

**Comment by ilich** [comment]
Please reopen the ticket if you will have sample solution for ASP.NET ReportViewer Control.
