### ISSUE TITLE
ASP.NET 5 Support?

### ISSUE THREAD

**Issue by anuraj** [ilich/MvcReportViewer#121]
Is MVCReportViewer supported in ASPNET 5?

**Comment by ilich** [comment]
It supports ASP.NET 5. Do you have an issue?

**Comment by anuraj** [comment]
No, someone asked me a question regarding ASP.NET 5 support for MVCReportViewer. I couldn't find any information related to that in the home page. So I asked that question. Thank you

**Comment by ilich** [comment]
No problem. The helper supports ASP.NET MVC 4 and 5. I am going to try it with ASP.NET MVC 6 with v0.8

**Comment by alzdrak** [comment]
Any feedback regarding support of ASP.NET 5 MVC 6?

**Comment by ilich** [comment]
I am going to take a look on November/December 2015 after ASP.NET 5 RC1.

**Comment by ilich** [comment]
I want to have release 0.8 finished and have MVC 6 support in 0.9.

**Comment by Asvictor** [comment]
Thx for providing such good tool.
But I have one silly question...
How to config the key="MvcReportViewer.ReportServerUrl"  value for .rdlc file? 
Since there is no ReportServer_SQLEXPRESS for it...
Thx a lot.

**Comment by ilich** [comment]
Please take a look to https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/LocalReports.cshtml example. I'd also recommend to download sample application and play with it.

**Comment by anuraj** [comment]
Is MVC Report Viewer supported in ASP.NET5 MVC 6?

**Comment by ilich** [comment]
You can try to use it. I think it will work out of box. I am going to do testing by the end of the year once I will have time.

**Comment by zeeshan4119** [comment]
The reportviewer is not showing the print button in Chrome and Firefox how can i display the print button?

**Comment by tiesont** [comment]
@zeeshan4119 That's a known issue with the report viewer, as the print button is an ActiveX control. There are a few methods you can use to essentially duplicate the same functionality. For example: http://www.neodynamic.com/articles/How-to-add-Cross-Browser-Printing-to-ASP-NET-ReportViewer-toolbar/

**Comment by ilich** [comment]
Please check this:

1. Make sure you have ~/Scripts/MvcReportViewer.js and ~/Scripts/url.js on the server. 

2. Check that you have jQuery references in MvcReportViewer.aspx.

```
<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
```

3. MvcReportViewer's **aspxViewerJavaScript** setting in Web.config is ~/Scripts/MvcReportViewer.js.

Run sample application from the repository and check if Print button works in your browser. If it does not work then there is an issue with your server setup and/or browser.

**Comment by ilich** [comment]
One more thing. Print button will render report to PDF which you can print from your web-browser or Acrobat reader. Printer printing is supported only in Internet Explorer because it required ActiveX support.

**Comment by golamkhan** [comment]
Just wondering how long it might take to release the support for ASP.NET 5 MVC 6?

**Comment by ilich** [comment]
I think it should work now. I will try to find time to test it. Have you tried to use MvcReportViewer with MVC 6? What issues have you experienced?

**Comment by golamkhan** [comment]
I added the reference to my view. But I don't find any helper method.

**Comment by ilich** [comment]
You should add ```@using MvcReportViewer;``` to your Razor file. Take a look to https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/Fluent.cshtml

**Comment by ilich** [comment]
Please let me know if you still have issues after the fix.

**Comment by golamkhan** [comment]
yes I added that

**Comment by ilich** [comment]
It seem that I will have to test the helper myself. I will try to do it later this week or next week. Please let me know if you will find the cause of the issue.

**Comment by golamkhan** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5931233/12099303/1a335350-b2ed-11e5-9f40-4ca4910a3ba8.png)
Please see the screenshot

**Comment by ilich** [comment]
OK. I will take a look. Thank you for the information. I am afraid I will have to create special fork for MVC 6.

**Comment by inu70** [comment]
hi, do you have a video tutorial about this is project ?

**Comment by ilich** [comment]
No, I do not have any video tutorials. I'd recommend you to take a look to the sample application I've built. I hope it will provide you enough information how to use the solution.

**Comment by inu70** [comment]
thakn so much for you respon my ask

oh ya, i have a problem to open your project
i can't to attach database.mdf to sql server 2008

this is error comment "cannot be opened because it is version 782. This server supports version 655 and earlier. A downgrade path is not supported."


any solution ?

**Comment by ilich** [comment]
Unfortunately you need Visual Studio 2015 and SQL Server 2014 Express for development.

**Comment by KerolosMalak** [comment]
@ilich  
Please let me know if you create a special version for ASP.NET Core 1.0
I am working on ASP.NET Core app when add package "MVCReportViewer" project fire error "**the dependency MVCReportViewer doesn't support framework .NetCoreapp**"

**Comment by yao-bin** [comment]
Please, how about the special fork for MVC 6?

**Comment by ilich** [comment]
ASP.NET Core fork sounds good. The only problem, I seee, MvcReportViewer uses Report Viewer Web Forms control. It does not seem that MS will support web forms for ASP.NET Core in the nearest future. Please let me know if I am wrong. Otherwise I am open for forks and pull requests because I am busy with other projects. Unfortunately, I do not use SSRS at work at the moment. This is the main reason why it is hard to find time for MvcReportViewer.

**Comment by tiesont** [comment]
Following through the referenced project above, https://github.com/alanjuden/MvcReportViewer looks interesting (assuming @ilich isn't going to be able to work on this project any time soon).

**Comment by yao-bin** [comment]
ok, thanks!

**Comment by ilich** [comment]
Unfortunately, ASP.NET Core does not support Web Forms and ReportViewer 2016 control is not going to work there. I am going to update the project to use the latest Report Viewer control, but it won't work on ASP.NET Core. Please use https://github.com/alanjuden/MvcReportViewer if you need ASP.NET Core support and do not use Microsoft implementation. My library is a wrapper around Microsoft component.

I hope, Microsoft will support web forms for ASP.NET Core in the future, and I will be able to bring the extension there.
