### ISSUE TITLE
Assembly fails when web application is deployed to production server

### ISSUE THREAD

**Issue by ecosme8** [ilich/MvcReportViewer#125]
Hello,

I have been testing my application on debug and everything works fine. I have deployed my application to a SQL 2008 R2 production server and when I try to load a report I get the following error:

 CS1705: Assembly 'MvcReportViewer, Version=0.7.5618.16305, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

I have installed the following package in my server: http://www.microsoft.com/en-us/download/details.aspx?id=577

Still my application is not working.

Please help

**Comment by tiesont** [comment]
I would update your application to https://www.nuget.org/packages/Microsoft.AspNet.Mvc/4.0.40804, and try re-deploying. Make sure the assembly is set to `CopyLocal=true` in your project references.

**Comment by ecosme8** [comment]
Thank you so much! This worked great for me, but know I am getting another problem when trying to generate the report. The problem I get is the following:

errorType=’Microsoft.Reporting.WebForms.LocalProcessingException’
error= ‘An error ocurred during local report processing’.

I'm trying to get the exception but I have not been successful

**Comment by tiesont** [comment]
I'm assuming you're attempting to use an .rdlc file?

If you're not already using it, something like ELMAH can be helpful, especially if you're trying to capture errors in production.

**Comment by ecosme8** [comment]
Yes, I'm attempting to use an .rdlc file. This is the code for the view:

@{
    ViewBag.Title = "LotReport";

    var settings = new ControlSettings
    {
        ShowParameterPrompts = false,
        ShowFindControls = true,
        BackColor = System.Drawing.Color.BurlyWood,
        KeepSessionAlive = true,
        Width = new System.Web.UI.WebControls.Unit("100%"),
        Height = new System.Web.UI.WebControls.Unit("100%"),
        AsyncRendering = false,
        SizeToReportContent = true,
        
    };
}

@model ReportApp.Models.LocalReportsModel
@using MvcReportViewer;
@using Microsoft.Reporting.WebForms;

<div class="container-fluid">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-xs-6 col-sm-3 col-lg-2 sidebar-offcanvas" id="sidebar">
            <div class="well">
                <h4>
                    Monitoring</h4>
                <ul class="list-group">
                    @Html.ActionLink("Transactions Log", "Index", "Monitor", null, new { @class = "list-group-item" })
                </ul>
            </div>
            <div class="well">
                <h4>
                    ASN-856</h4>
                <ul class="list-group">
                    @Html.ActionLink("Shipment Level", "Index", "Transaction", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Order Level", "Index", "OrderLevel", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Tare Level", "Index", "TareLevel", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Pack Level", "Index", "PackLevel", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Inner Pack Level", "Index", "InnerPackLevel", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Item Level", "Index", "ItemLevel", null, new { @class = "list-group-item" })
                </ul>
            </div>
            <div class="well">
                <h4>
                    Reports</h4>
                <ul class="list-group">
                    @Html.ActionLink("Dashboard", "Index", "Report", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Lot Report", "LotReport", "Report", null, new { @class = "list-group-item active" })
                    @Html.ActionLink("Lot Expiration Report", "LotExpirationReport", "Report", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Order Report", "OrderReport", "Report", null, new { @class = "list-group-item" })
                </ul>
            </div>
        </div>
        <div class="col-xs-12 col-sm-9">
            <p class="pull-left visible-xs">
                <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">
                    Toggle nav</button>
            </p>
            
            <div class="col-md-12 col-lg-12 col-xs-12 col-sm-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Report Parameters
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("LotReport", "Report", FormMethod.Post, new { @class = "form-inline" }))
                        {
                            <div class="table-responsive">
                                <table class="table table-condensed">
                                    <tr>
                                        <td>
                                            <label class="labelFont">
                                                &nbsp;</label>
                                            <div class="form-group">
                                                <button class="btn btn-success" type="submit" style="font-size: small;">
                                                    Generate Report</button>
                                            </div>
                                        </td>
                                        <td>
                                            <label>
                                                Lot Number</label>
                                            <div class="form-group">
                                                @Html.TextBox("lotNumber", null, new { @class = "form-control", @id = "lotNumber" })
                                                @*<input type="text" class="form-control" id="lotNumber" /> *@
                                            </div>
                                        </td>
                                        <td>
                                            <label>
                                                National Drug Code</label>
                                            <div class="form-group">
                                                @Html.TextBox("productId", null, new { @class = "form-control", @id = "productId" })
                                                @*<input type="text" class="form-control" id="productId" />*@
                                            </div>
                                        </td>
                                        <td>
                                            <label>
                                                Order Number</label>
                                            <div class="form-group">
                                                @Html.TextBox("orderNumber", null, new { @class = "form-control", @id = "orderNumber" })
                                                @*<input type="text" class="form-control" id="orderNumber" />*@
                                            </div>
                                        </td>
                                        <td>
                                            <label class="labelFont">
                                                Record Quantity</label>
                                            <div class="form-group">
                                                <select class="form-control selectpicker" id="recordQuantity" name="quantity">
                                                    <option value="100">100</option>
                                                    <option value="500">500</option>
                                                    <option value="1000">1000</option>
                                                    <option value="all" data-toggle="tooltip" data-placement="right" 
                                                        title="Choosing 'All' may retrieve more than 1,000 records. Please wait for the report to be loaded."
                                                        id="allRecords">All</option>
                                                </select>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                                
                            </div>
                            
                        }
                    </div>
                    
                </div>
                
            </div>
            <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" style="padding-top: 15px;" id="reportDiv">
             @if (TempData["ViewReport"] != null)
                {
                    if (Convert.ToBoolean(TempData["ViewReport"]))
                    {
                        @Html.MvcReportViewerFluent("App_Data/Reports/LotReport.rdlc").ProcessingMode(
                        ProcessingMode.Local).Attributes(
                        new { Height = 1000, Width = 1000, style = "border: none" }).Method(
                        FormMethod.Post).LocalDataSource(
                        "ReportDataset", @Model.Items).ControlSettings(settings)

                    }
                }
            </div>
        </div>
    </div>
    <div id="confirmDialog" title="Confirm">
        <p>
            The record may contain more than 1,000 records, do you wish to proceed?
        </p>
    </div>
    @if (TempData["message"] != null)
    {
        <div id="noRecordsDialog" title="No records!">
            @TempData["message"].ToString()
        </div>
    }
</div>



Im not sure if the @using clauses are working in the deployed server...

**Comment by tiesont** [comment]
Can you trim that back to the minimum required to get the same error? There's an awful lot of extraneous code there.

Also, Github uses three backticks for code blocks. So ` ` ` (without the spaces).

**Comment by ecosme8** [comment]
Okay, I have noticed that in the deployment of the application the rdlc files where not in the server. I have passed the files to the server in the App_Data/Reports folder where all my files are located. When I try to generate it takes some seconds to load but still fails.

**Comment by tiesont** [comment]
Do your reports use an embedded connection string, or a named connection? If the later, is the connection string configured in the connectionStrings section in your web.config?

**Comment by ecosme8** [comment]
Ok, the connection string to the database is declared in the web.config file. My reports does not have any connection string embedded. This is part of my web.config file:

<add key="MvcReportViewer.AspxViewer" value="~/MvcReportViewer.aspx" />
    <add key="MvcReportViewer.AspxViewerJavaScript" value="~/Scripts/MvcReportViewer.js" />
    <add key="MvcReportViewer.ErrorPage" value="~/MvcReportViewerErrorPage.html" />
	  <add key="MvcReportViewer.ShowErrorPage" value="True" />
	  <add key="MvcReportViewer.ReportServerUrl" value="http://localhost/ReportServer_SQLEXPRESS" />
	  <add key="MvcReportViewer.Username" value="" />
	  <add key="MvcReportViewer.Password" value="" />
    <add key="MvcReportViewer.EncryptParameters" value="False" />
    <add key="MvcReportViewer.LocalDataSourceProvider" value="MvcReportViewer.SessionLocalDataSourceProvider, MvcReportViewer" />

**Comment by tiesont** [comment]
This:

    <add key="MvcReportViewer.ReportServerUrl" value="http://localhost/ReportServer_SQLEXPRESS" />

is not likely to work on a "real" server, unless your SQL Server runs on the same machine that IIS runs on (even then, I don't think localhost would resolve properly, but I'm not really a "server guy", so...). I'd use the same URL as you would give, say, Server Management Studio if you were connecting remotely.

**Comment by ilich** [comment]
Please review https://social.msdn.microsoft.com/Forums/en-US/1cc77647-aaa0-4860-b976-671a513220ea/microsoftreportingwebformslocalprocessingexception-was-unhandled-by-user-code?forum=vsreportcontrols and https://rusirub.wordpress.com/2008/05/09/microsoft-report-viewer-deployment-issues/

We need full exception stack trace to find out what's going on on your server.

**Comment by ecosme8** [comment]
Well, I followed the instructions on the second link you gave me, I do have the Microsoft.ReportViewer.ProcessingObjectModel.DLL in the server. I tried to get a full exception stack trace but I dont know how to... I turned off the MvcReportViewer.ShowErrorPage but doesn't display anything at all...

**Comment by ilich** [comment]
1. Make use you have http://www.microsoft.com/en-us/download/details.aspx?id=35747 installed on the server
2. Check reports file system permissions
3. If it still does not work, try to create a blank report and deploy it. You can use sample reports from the sample application. I think it may be that your web-application does not have some permissions (I do not know which one) or report viewer running out of memory,\

**Comment by ecosme8** [comment]
I have installed the microsoft report viewer runtime but for SQL Server 2008 R2, do I still have to install the 2012 version?

**Comment by ilich** [comment]
Yes, you should. It might be  the reason why you report is failing.

**Comment by ecosme8** [comment]
YES! That fixed the problem, installing the package and when I ran it it worked. Thank you so much.

**Comment by ilich** [comment]
Awesome!
