### ISSUE TITLE
Server not finding ScriptResource.axd and Sys not defined: MvcReportViewer.aspx

### ISSUE THREAD

**Issue by ecosme8** [ilich/MvcReportViewer#126]
Hello,

I am having a problem trying to generate report in an SQL 2008 R2 Server. The report gets generated without data and I get the following error in the browser console:

http://172.16.100.49/edivisualizer/ScriptResource.axd?d=0EH49AIZaa_QXbaR95nb0eVQTveK7piGmulKVoy6-mzlqEwpnGVK3hmRFG1weFAskPvKbn3yLlBEDc6fFS2TWcKx3YSykz58nU9BAvdb9Atm-ZsnTkt5q9y3UTZ9fttC-wDXR7_9ScPYncrg1gcusBGxq4E9bmzT6M_9eM4_cV81&t=7e632e9f

Failed to load resource: the server responded with a status of 404 (Not Found)

http://172.16.100.49/edivisualizer/Reserved.ReportViewerWebControl.axd?OpType=Resource&Version=11.0.3452.0&Name=ViewerScript

Uncaught ReferenceError: Type is not defined

MvcReportViewer.aspx:53 
Uncaught ReferenceError: Sys is not defined

Please I need to know what is going wrong with this.

**Comment by ilich** [comment]
I have never seen the issue before. Something is wrong with Report Viewer Web Control configuration.

Try this:
http://blogs.msdn.com/b/vijaysk/archive/2009/01/14/report-viewer-toolbar-does-not-render-properly-on-iis-7-0.aspx
http://www.smarterasp.net/support/kb/a433/404-not-found-reserved_reportviewerwebcontrol_axd-reportviewer.aspx
http://ericphan.net/blog/2008/12/8/reservedreportviewerwebcontrolaxd-not-found.html
http://stackoverflow.com/questions/12488845/the-report-viewer-web-control-http-handler-has-not-been-registered-in-the-applic

**Comment by ecosme8** [comment]
Ok I tried the first two links, but know I'm getting a Server Error:

405 - HTTP verb used to access this page is not allowed

The server is not allowing me to use MvcReportViewer.aspx

**Comment by ilich** [comment]
You should check what verbs are allowed in IIS.

http://stackoverflow.com/questions/6739124/iis-7-5-enable-put-and-delete-for-restful-service-extensionless

http://forums.asp.net/t/1805650.aspx?405+HTTP+verb+used+to+access+this+page+is+not+allowed+IIS+7+

I think you should allow at least GET, POST, HEAD


Also check this: https://msdn.microsoft.com/en-us/library/ms251661.aspx

**Comment by ecosme8** [comment]
Still I cant make it work... In chrome i get this error:

POST http://172.16.100.49/edivisualizer/MvcReportViewer.aspx 405 (Method Not Allowed)

**Comment by ilich** [comment]
It might be an authentication issue as well. Try to provide Windows username and password to the viewer config. The user must be a valid user on the SSRS server.

https://social.msdn.microsoft.com/Forums/en-US/353ad925-80f3-4d2f-a6ef-b66d4fd122ab/deploying-my-app-getting-error-http-status-405-method-not-allowed?forum=sqlreportingservices

If it still does not work then I'd recommend to try to build a simple Web Forms application and to render report using this app. It may help you to find out if there is a bug in the MvcReportViewer or this is server configuration issue.

You can also post a question to http://forums.asp.net/ or stackoverflow, but ask about ReportViewer Web Control. There might be somebody who experienced the same issue before.
