### ISSUE TITLE
toolbar compatibility issue with IE 11 and Chrome

### ISSUE THREAD

**Issue by Lfwinster** [ilich/MvcReportViewer#127]
Hi, today I was testing this helper out then I ran into the following problems:

1.Setting AsyncRendering to true cause the image in the report won't show properly in IE 11 but not in Chrome. If not true, then IE 11 will suffer a 20-second-ish freeze while Chrome won't.
2. PrintButton is not showing properly(whether ShowPrintButton is true or not) in Chrome and the behavior is not prompting a print dialog but directly downloading a pdf file.

Here is the code I am using and the screenshot:

@(
 Html.MvcReportViewerFluent("")
.ProcessingMode(Microsoft.Reporting.WebForms.ProcessingMode.Remote)
.ReportServerUrl("blahblahblah ")
.ReportParameters(new { blahblahblah })
.ReportPath("blahblahblah ")
.Attributes(new { Width = 1200, Height = 600 })
    .ControlSettings(new ControlSettings() { 
        AsyncRendering = true, 
        ShowToolBar=true
        ,KeepSessionAlive = true
        ,ShowParameterPrompts=false
        ,ShowFindControls = false
        ,ShowExportControls = true
        ,ShowPrintButton = true
        ,ShowZoomControl =true
        ,ShowPageNavigationControls = true,
    })
)

Chrome:

![image](https://cloud.githubusercontent.com/assets/8297318/10401428/e326ab22-6e8c-11e5-8eff-91bbd0db7568.png)

IE 11:
![image](https://cloud.githubusercontent.com/assets/8297318/10401398/a9e47b6e-6e8c-11e5-9d78-bc2a13baf6a2.png)

**Comment by Lfwinster** [comment]
I just reviewed other closed issues and the print button is exporting pdf that I understand now, but can you make it not showing when ShowPrintButton is set to false?

**Comment by ilich** [comment]
Yes, I will add this fix to release 0.8. Thank you for the feedback.
