### ISSUE TITLE
Loss the asp.net session...

### ISSUE THREAD

**Issue by johnluukas** [ilich/MvcReportViewer#128]
I have an application in mvc with windows authentication, And when I want to see a report by controlling it tells me that the session of asp.net has expired or is not, This leaves me at the time that the ReportViewer headers are painted and loading window appears

**Comment by ilich** [comment]
It seems to be application or server configuration issue. Please check http://forums.asp.net/t/1238835.aspx?Asp+Net+session+has+expired+in+reportviewer+control and http://stackoverflow.com/questions/3361612/how-to-handle-report-viewer-session-expired-exception 

If the articles does not help then build simple Web Forms application using Report Viewer Web Control and see if it works in your environment or not. 

Please create a bug report if there is an issue in MvcReportViewer.

Unfortunately I do not have enough information to provide you more information at this time.
