### ISSUE TITLE
Javascript/JQuery hang when ReportView page is loading

### ISSUE THREAD

**Issue by Lfwinster** [ilich/MvcReportViewer#129]
Hi, MvcReportViewer is running smoothly. The only issue right now is when the report viewer is rendering a report. all js functions/ jquery calls would just freeze until the render is complete. It doesn't matter which page you are interacting with. For example I have a JQuery call to an action in another controller. when the report is running, then I make that call. It won't even hit the breakpoint I set up in the controller until the report viewer finishes.

p.s. when I say rendering I mean that "Loading" icon is spinning on the page.

**Comment by ilich** [comment]
Unfortunately this is ReportViewer Web Control behavior. You can try Asynchronous Rendering. Set AsyncRendering = True in the report viewer configuration.

https://msdn.microsoft.com/en-us/library/ms252090.aspx

**Comment by Lfwinster** [comment]
Yeah that is what I assume and unfortunately I already set async rendering to true. It's even worse if I don't do so.

**Comment by Lfwinster** [comment]
I wonder what is gonna happen when SSRS 2016 comes out and how to migrate.

**Comment by ilich** [comment]
Well, if MS will release new version of Report Viewer library then I am going to use it for MvcReportViewer. You will have to update the package. I think that new version will be backward compatible.

**Comment by Lfwinster** [comment]
That will be awesome. Thanks!
