### ISSUE TITLE
rc:DocMap=false|true

### ISSUE THREAD

**Issue by TomSimonsen** [ilich/MvcReportViewer#130]
Hi!

I got a report with document map, is it possible to hide this map if needed with @Html.MvcReportViewerFluent?

Thanks,
TomS

**Comment by ilich** [comment]
You cannot pass the parameter to Reporting Server URL. At least, I haven't found how to do it with Report Viewer Web Control. MvcReportViewer is just a wrapper around the control provided by Microsoft.

Please take a look to those threads. They might be helpful:

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a737fdc3-6845-4304-b305-2f3c693b9599/hide-dcoument-map-by-default-while-viewing-the-report-in-ssrs?forum=sqlreportingservices

http://stackoverflow.com/questions/11722095/asp-net-reportviewer-cannot-hide-the-document-map
