### ISSUE TITLE
Local Report Enable Hyperlinks Property

### ISSUE THREAD

**Issue by StanSeddon** [ilich/MvcReportViewer#131]
Could the LocalReport.EnableHyperLinks property be exposed please.

**Comment by ilich** [comment]
The change will be release in 0.8. Thank you for the idea!

**Comment by StanSeddon** [comment]
Thanks.

That’s brilliant.

I work for the National Health Service in the UK. The systems that this has been used for help the health of around 10 million people. Just thought that I would let you know about the positive impact of the work you are actually doing.

Thanks again.

Stan

Stan Seddon
Development Manager
North West Commissioning Support Unit (NWCSU)

www.northwestcsu.nhs.uk<http://www.northwestcsu.nhs.uk/>
Follow us on Twitter: @NorthWestCSU

**Comment by gitsubash** [comment]
I am using the version 0.8.581.27247 (just downloaded yesterday) but not getting the problem of hyperlinks solved.
My reports has the latitude and longitude which will hyperlink to the google maps. So, Am i missing something to enable them? I am very new in using your mvcreportviewer. The error goes like this:

"Report 'ActivityReport' contains hyperlinks. The EnableHyperlinks property has not been set for this reportÈ

Where should I enable the hyperlink property
