### ISSUE TITLE
Why is there a separate print button for non-ie?

### ISSUE THREAD

**Issue by ChuckBryan** [ilich/MvcReportViewer#132]
Love the tool. I was wondering why there is a separate print button for non-ie? I had not noticed it, but, one of my users pointed out that it appears below the main bar when viewing in chrome. I looked at the MvcReportViewer.aspx and sure enough, it does. I am assuming that there is an issue that you were working around?

**Comment by ilich** [comment]
Report Viewer Web control provided by Microsoft supports Print functionality only from Internet Explorer. This is the reason why Print button in Chrome and Firefox "prints" to PDF.

Thank you for the bug report. I will take a look to UI in Google Chrome.

**Comment by ChuckBryan** [comment]
Thank you for the explanation.

**Comment by ilich** [comment]
Please deploy the latest nuget package.

**Comment by ilich** [comment]
And make sure you clients has cleaned browser cache.

**Comment by ChuckBryan** [comment]
Thank you! This looks great!

**Comment by ChuckBryan** [comment]
One last clarification...Should the Print Button in Chrome be saving to PDF? Or should I expect it bring up a print dialog? Currently it is going to PDF.

**Comment by ilich** [comment]
Report Viewer Web Control uses ActiveX to print its content. It works only in Internet Explorer. If you will try to use Report Viewer from a web forms application there will be no Print button in Chrome or Firefox.

I use save to PDF as a workaround, because it is easy to open PDF and print it if needed.

**Comment by ChuckBryan** [comment]
Thank you again for the further explanation. Ah, Active X...those were the days!
