### ISSUE TITLE
Dynamic size

### ISSUE THREAD

**Issue by SmutsMuts** [ilich/MvcReportViewer#133]
Hello,

So I was wondering if there is any way to get the iframe to take up the full size of the report. So you use the scrollingbars in the browser instead of using scrolling bars in the iFrame. 
It doesn't look that nice if you set a height of say 900 and you have a larger screen, then the scrollbar isn't the full page height.
Right now I have a timer which corrects the size like each halv second or something. I would like to remove this ugly piece  :P

**Comment by ilich** [comment]
Hello,

Unfortunately I haven't seen any good solution for this task. I think it is common to use JS as a workaround. Feel free to send a pull request if you will find good solution.
