### ISSUE TITLE
RDLC rendering

### ISSUE THREAD

**Issue by bxbxbx** [ilich/MvcReportViewer#134]
Any chance for RDLC rendering.

Not everybody has a ReportingSvc server at their hands

**Comment by ilich** [comment]
Please take a look to https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/LocalReports.cshtml example. I'd also recommend to download sample application and play with it.

**Comment by bxbxbx** [comment]
Tnx for the quick reply, great work!

BUT now I have a strange problem, the control keeps giving me a "Report not defined" exception, raised in the ReportViewerParametersParser.Parse method.

I traced it back to the fact the the Request.Form collection is empty, so the control tries to get the parameters from the query string, which of course is also emtpy.

I'm on NET4 , MVC4 and using the FluentDemoCode from the samples.

The view looks like this:

```
@using Microsoft.Reporting.WebForms
@using MvcReportViewer

@model REC.ParameterManager.Controllers.Audit
@{
    ViewBag.Title = "Parameter Audit";
}

@Html.MvcReportViewerFluent("App_Data/AuditLog.rdlc").ProcessingMode(ProcessingMode.Local).ReportServerUrl(string.Empty).Method(FormMethod.Post).ReportParameters(new { Bereich = "VBT" }).LocalDataSource("DataSet1", Model.Table).Attributes(new { Height = 900, Width = 900, style = "border: none" })
```

I looked for 3h, but now I'm without any more clues.
Can you point me in the right direction?

**Comment by ilich** [comment]
Make sure you have local data source provider registered in your application. Take a look to https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Web.config file (line24)

If you are using IoC in the application then check how you can register it in https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/App_Start/NinjectWebCommon.cs file

I would recommend you to download sample application. It has build-in local reports. You can learn how to use them there.

**Comment by ilich** [comment]
One more thing. You should use `.ReportServerUrl(string.Empty)` call to render local report.This is sample code how to use local reports:

`@Html.MvcReportViewerFluent("App_Data/Reports/Products.rdlc").ProcessingMode(ProcessingMode.Local).ReportParameters(new { Parameter1 = "Test", Parameter2 = 123 }).LocalDataSource("Products", Model.Products).LocalDataSource("Cities", Model.Cities).Attributes(new { Height = 900, Width = 900, style = "border: none" }).Method(FormMethod.Post)`

**Comment by bxbxbx** [comment]
Just wanted to let you know that I nailed it down today!

Believe it or not, but It had to do with the configured session handling in my solution.
I used cookieless sessions and this seems not to work well with IIS Express, since in the Postback call to your webform, all session data ist gone.

Whats even stranger is the fact, that also the form parameters were gone, so neither Post nor Get would work for me.

I switched to sessions with cookies, and it worked right away!
Maybe this is something that should be further investigated, or at least documented!

I have no idea if this applies also for IIS.

**Comment by ilich** [comment]
The reason is MvcReportViewer is not able to find user session since the session ID should be passed through URL. I will try to support cookie less sessions in the control.

**Comment by ilich** [comment]
Unfortunately you will have to use ASP.NET Web Forms solution hosted in an iframe to solve the problem quickly.

**Comment by ilich** [comment]
I have created the fix. Please take the latest code from github and build it. I am going to release updated nuget package once the other ticket for 0.8.5 release is ready to go.
