### ISSUE TITLE
LocalMode fails to evaluate expression

### ISSUE THREAD

**Issue by splendid25** [ilich/MvcReportViewer#135]
Hello,
I have a simple RDLC report with a TextBox with the following value :
=Globals!ExecutionTime

I use MvcReportViewer with the 4.5 Framework. The report displays correctly, but this expression fails and displays #Error. The rest of the report is OK.

Apparently a single line should fix the problem :
localReport.SetBasePermissionsForSandboxAppDomain(
    AppDomain.CurrentDomain.PermissionSet.Copy());
Source : https://stackoverflow.com/questions/6347125/reportviewer-2010-fails-to-evaluate-expressions

Is it possible to add a parameter to the FluentApi to activate this option?

Or maybe I missed something an existing setting?

Thanks

**Comment by ilich** [comment]
Sure, I will add this setting to the configuration.

**Comment by ilich** [comment]
Please use nuget package v0.8.2.

**Comment by splendid25** [comment]
It's perfect, thanks :)
