### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by scurenton** [ilich/MvcReportViewer#139]
Is there a way to use a progress bar with this?  Never used one before, but my page loads and then the report loads.  I would like to have a progress bar show that the report is loading

**Comment by ilich** [comment]
That's what I'd do.

* Add a class to report's iframe.
```
@Html.MvcReportViewerFluent("App_Data/Reports/Cities.rdlc").ProcessingMode(ProcessingMode.Local).Method(FormMethod.Post).LocalDataSource("Cities", Model.FilteredCities).Attributes(new { Height = 900, Width = 900, style = "border: none", @class="report_1" })
```

* Show a progress bar on document.ready event.

```
$(document).ready(function () {
    console.log("show progress bar");
});
```

* Hide the progress bar on iframe.load event.
```
$(".report_1").load(function () {
    console.log("hide progress bar");
});
```

**Comment by scurenton** [comment]
Worked like a champ! Thanks for your direction
