### ISSUE TITLE
Dynamic Connection String

### ISSUE THREAD

**Issue by tvblomberg** [ilich/MvcReportViewer#140]
Hello Ilya,

Thank you for creating an MVC Report Viewer. I have an issue I was hoping you could help me with.

I was using a trial version of Syncfusion to do most of this, and thought I would give MvcReportViewer a try. In my report definition I have a parameter called connectionString so I can set the data source dynamic. How I did this in Syncfusion is I just passed it as a parameter to the embedded data source. I tried to do the same with MVC Report Viewer, but I am getting this error:

Microsoft.Reporting.WebForms.ReportServerException: The+current+action+cannot+be+completed.+The+user+data+source+credentials+do+not+meet+the+requirements+to+run+this+report+or+shared+dataset.+Either+the+user+data+source+credentials+are+not+stored+in+the+report+server+database,+or+the+user+data+source+is+configured+not+to+require+credentials+but+the+unattended+execution+account+is+not+specified.+(rsInvalidDataSourceCredentialSetting)

I know that the credentials are correct as I am using the same connection string with the Syncfusion trial. Have you ran into this before?

Here is my HTML Helper code:

@Html.MvcReportViewer(
			"/TestReport/Test",
			new { customerId = "Test", connectionString = "Data Source=Test;Initial Catalog=Test; User Id=Test; Password=Test" },
	new { Height = 900, Width = 900, style = "border: none" })

I appreciate any help you can offer!

Thanks,
-Tommy

**Comment by ilich** [comment]
Hello Tommy,

I have never tried dynamic connection strings at SSRS. I hope https://stackoverflow.com/questions/19827625/ssrs-report-dynamic-connection-string-and-parameters will be helpful.

Regarding your exception. Please check SSRS username, password and server. They are specified in Web.config (https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Web.config, line 13).

If it still does not work then I'd recommend you to take a look to SSRS documentation and check its settings.

https://msdn.microsoft.com/en-us/library/ms160330.aspx

https://msdn.microsoft.com/en-us/library/ms156302.aspx

The easiest way to test your settings is to build simple web form with Report Viewer Web Control and check either it is working or not.

Thank you for using MvcReportViewer!

Sincerely,
Ilya
