### ISSUE TITLE
Defaulting windows authentication for username and password

### ISSUE THREAD

**Issue by jfakey** [ilich/MvcReportViewer#141]
Is there a way to pass the default windows authentication into this in the web.config file

<MvcReportViewer reportServerUrl="http://localhost/ReportServer_SQLEXPRESS"
                   username="" 
                   password=""
                   ....
>

or here?

<add key="MvcReportViewer.Username" value="" />
<add key="MvcReportViewer.Password" value="" />

Thanks in advance

**Comment by ilich** [comment]
Yes, you can. If you set username and password to be an empty string, Report Viewer Web Control will use you App Pool username to authenticate on SSRS.

**Comment by ilich** [comment]
I setup my development machine with username="" and password="" to launch sample application on IIS Express.

**Comment by jfakey** [comment]
Thanks, that is what I thought, did not want to take the time to install
and configure everything if not the case.

Great work on this, thanks again
