### ISSUE TITLE
Local Reports

### ISSUE THREAD

**Issue by rodrigomocca** [ilich/MvcReportViewer#142]
Sorry if an issues is not the way to make a questions, but i dont find another way.
How do I use this framework without ssrs? Y have .rdlc files and i want to show they with ReportViewer.
Thanks you.

**Comment by ilich** [comment]
Please take a look to https://github.com/ilich/MvcReportViewer/tree/master/MvcReportViewerExample project. It has Local Reports samples.

https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Controllers/HomeController.cs (line 110)

https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/LocalReports.cshtml

https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Web.config (line 13)

https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/App_Start/NinjectWebCommon.cs (line 49)
