### ISSUE TITLE
Report parameters not working in ProcessingMode.Local?

### ISSUE THREAD

**Issue by chrigu-ebert** [ilich/MvcReportViewer#143]
Hi there,

I tried to display a parameter in my report but it just displays "#Fehler" (#Error) instead of the actual value. I used the Controller-Extension method and pass the parameter as you mentioned in the documentation:

this.Report(ReportFormat.Pdf, "ReportWeekly.rdlc", new { ReportParameter1="Test" }, ProcessingMode.Local, reportDataSource);

Is that supposed to work with a local report? Unfortunately I can't build your project from source as you are using C# 6 features and I'm still running on VS2012 :(

Best,
Chris

**Comment by ilich** [comment]
Yes, report parameters should work. #Error means there is an error in the report itself, e.g. division by zero, etc. I'd recommend you to host your report in simple ASP.NET Web Forms page and tune it there. 

Make sure you have Local Data Source Provider  registered in your Web.config or Dependency Injection configuration (check README.md and https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/App_Start/NinjectWebCommon.cs)

**Comment by ilich** [comment]
Please reopen the ticket if there is a bug in MvcReportViewer. I will need steps to recreate it as well.
