### ISSUE TITLE
Subreport RDLC Example is required

### ISSUE THREAD

**Issue by elwolfy** [ilich/MvcReportViewer#148]
I have tried to run un subreport using the "SubreportProcessingEventHandler" but It not fire the event:
<addr>
            reportViewer.LocalReport.SubreportProcessing += new SubreportProcessingEventHandler(SetSubDataSource);            
            reportViewer.LocalReport.Refresh();
</addr>

The call to  SetSubDataSource is not happened.
<addr>
        public void SetSubDataSource(object sender, SubreportProcessingEventArgs e)
        {
           e.DataSources.Add(new ReportDataSource("DataSet1", dsAnexo111.Tables[1]));
           
        }
</addr>
Maybe,somebody can provide an example related to subreport RDLC with MvcReportViewer.

Any help will be appreciated.
Thanks in advance.

**Comment by ilich** [comment]
Sure. There is an example in MvcReportViewer sample application. You will need Visual Studio 2015 to build the project.

https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/Subreport.cshtml
