### ISSUE TITLE
The resource cannot be found Requested URL: /MvcReportViewer.aspx

### ISSUE THREAD

**Issue by boomgetchopped** [ilich/MvcReportViewer#149]
Hello,

I'm using nuget version 0.4.0 because I'm still using mvc 4.0.0.0 and I was getting a version error on your last few builds.

Anyway, I'm receiving the error above on IIS.  I do NOT receive this error when running localhost through visual studio.

**Comment by ilich** [comment]
Check your Web.config.
```<add key="MvcReportViewer.AspxViewer" value="~/MvcReportViewer.aspx" />``` should point to MvcReportViewer.aspx file. Try to request MvcReportViewer.aspx in the browser.

Also make sure you have all Report Viewer web control installed on the server.

**Comment by boomgetchopped** [comment]
If I try to navigate to mvcreportview.aspx directly I get:


Report is not specified. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: MvcReportViewer.MvcReportViewerException: Report is not specified.

Source Error: 


 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 



[MvcReportViewerException: Report is not specified.]
   MvcReportViewer.ReportViewerParametersParser.Parse(NameValueCollection queryString) +1084
   MvcReportViewer.MvcReportViewer.ShopReport() +109
   System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e) +25
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3064

**Comment by ilich** [comment]
MvcReportViewer renders an iframe on the page. Please check its src. You can also check HTTP requests using Fiddler tool to find out what's going on when you request MvcReportViewer.aspx.

**Comment by ilich** [comment]
Also set ```<add key="MvcReportViewer.ShowErrorPage" value="False" />``` in Web.config to disable error pages.

**Comment by boomgetchopped** [comment]
Thanks.  If I change it from a relative path to absolute it works.  Is there any way to include the path or make it work with relative?

**Comment by ilich** [comment]
I am glad to know that you found the problem.

You can change viewer's path in Web.config:
```<add key="MvcReportViewer.AspxViewer" value="~/MvcReportViewer.aspx" />```
