### ISSUE TITLE
HTML Viewer Commands

### ISSUE THREAD

**Issue by jglisson** [ilich/MvcReportViewer#151]
Great project, thanks for the work.

Do you have any guidance for modifying the HTML Viewer Commands (rc:Parameters, etc.)?

(https://technet.microsoft.com/en-us/library/ms152835(v=sql.105).aspx)

Thanks!

**Comment by ilich** [comment]
MvcReportViewer uses Report Viewer Web Control developed by Microsoft. I haven't found the way to use rc:* parameters there. Please send me sample code which passes the parameters to Report Viewer Web Control. I'd like to add this feature to the wrapper if it is possible.

**Comment by ilich** [comment]
Please reopen the ticket once you will have the sample.

**Comment by jglisson** [comment]
I got it working the way I wanted to by modifying this...

<rsweb:ReportViewer ID="ReportViewer" ClientIDMode="Predictable" runat="server" **ShowParameterPrompts="false"**></rsweb:ReportViewer>

**Comment by ilich** [comment]
You can achieve the same using https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewer/ControlSettings.cs class. You can take a look to https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/Fluent.cshtml to learn how use Control Settings.
