### ISSUE TITLE
MvcReportViewer error on IIS 7.5 with report use matrix > 40 columns

### ISSUE THREAD

**Issue by cuongbk81** [ilich/MvcReportViewer#152]
I use MvcReportViewer solution for report.
I have a report use matrix for bind data, it has > 40 columns. 
Report work done on IIS express (visual studio 2013) but deploy on IIS 7.5 it doesn't work.
I debug it and catch exception:An unhandled exception of type 'System.StackOverflowException' occurred in Microsoft.ReportViewer.Common.dll
I test report error when number of columns greater 40 columns. When number of column of matrix less than 40, report work done!
What problem with IIS 7.5 configuration? Please help to check it, tks.

**Comment by ilich** [comment]
Please send me full exception information. I have to take a look to the stack trace.

It'd be nice if you will attach a screenshot.

**Comment by cuongbk81** [comment]
<img width="1319" alt="screen shot 2016-02-03 at 11 03 57" src="https://cloud.githubusercontent.com/assets/15668964/12772774/41eee5d0-ca67-11e5-9219-72cc9eb8d4ad.png">
This is my report with ~ 54 columns on matrix
<img width="890" alt="screen shot 2016-02-03 at 11 07 50" src="https://cloud.githubusercontent.com/assets/15668964/12772782/543be300-ca67-11e5-8711-54999b1292d7.png">
This is exception catch by w3w on VS 2013 (host on IIS 7.5 windows server 2008 r2)
I move matrix to table, report work done with 54 columns

**Comment by ilich** [comment]
It seems to be an issue in Microsoft Report Viewer Web Control itself. Please try to run your report in ASP.NET Web Forms application to proof it.

**Comment by ilich** [comment]
You can try to create an issue at https://connect.microsoft.com/. MS support is very good. They've already fixed a few issues I found in their products.
