### ISSUE TITLE
Send parameters to server like URL Access Syntax

### ISSUE THREAD

**Issue by BehrouzTorabi** [ilich/MvcReportViewer#155]
Dear Contributors,
Hi,
At first, I wanna say thanks for the excellent helper you developed.
I asked a question on StackOverflow ([Link](http://stackoverflow.com/questions/35265637/url-parameters-in-mvcreportviewer)) about passing parameter with server URL (such as parameters with rs prefix or dsu prefix).
But now I think Its not implemented in MVCReportViewer, Is that wrong? If its false, how can I do this in MVCReportViewer ?

Thanks a lot
Behrouz

**Comment by ilich** [comment]
MvcReportViewer uses MS Report Viewer under the hood. Unfortunately MS Report Viewer Web Control does not provide this functionality, or I haven't found how to do it yet. Checks #151 for details.
