### ISSUE TITLE
Mvc Report Viewer doesn't work after publishing

### ISSUE THREAD

**Issue by HanaYehia** [ilich/MvcReportViewer#156]
I added a report viewer and tested it before the publish and worked , but after publishing it gives an exception 
`Microsoft.Reporting.WebForms.LocalProcessingException'
error='An+error+occurred+during+local+report+processing.'`

Here's the code I am using :
`Html.MvcReportViewerFluent("App_Data/EV-HR.rdlc").ProcessingMode(ProcessingMode.Local).LocalDataSource("DataSet1", Model).Attributes(new { Height = 900, Width = 900, style = "border: none" }).Method(FormMethod.Post)
`

**Comment by ilich** [comment]
The exception means that MvcReportViewer is working, but there is something wrong with the report. I cannot tell you what exactly is wrong over there without access to the server. 

Some ideas:

1. Make sure that you have all MvcReportViewer prerequisites installed on the server. Check the Installation part in https://github.com/ilich/MvcReportViewer/blob/master/README.md.

2. Enable default ASP.NET exceptions page in the Web.config (showErrorPage = true at Web.configm check the README.md file and sample application for the details)

3.  Make sure your report has been published.

4. Make sure IIS account/Application pool account has access to App_Data and your rdlc files.

I think that's all what I can think of based on the information you've provided.
