### ISSUE TITLE
How do I configure to work with SQL 2014 SSRS?

### ISSUE THREAD

**Issue by dave-007** [ilich/MvcReportViewer#157]
Have attempted to refer to the SQL 2014 SSRS controls with no success, basically changing from version 11 to version 12 in web.config, and have updated the gac reference to Microsoft.ReportViewer.WebForms to reflect version 12.0.0.0:

      
What else is required to work with SSRS in SQL 2014?

**Comment by ilich** [comment]
I am developing using 12.0.0.0, and I have never had issues with this version. Please try to diff your Web.config and my Web.config from the Sample application. 

Also make sure you are using the latest NuGet package.

**Comment by ilich** [comment]
I haven't installed or configured anything special to use SSRS 2014.

**Comment by dave-007** [comment]
Set all my versions back to 11, removed the Microsoft.ReportViewer.WebForms reference and re-added the 11 version and got it working. Thanks for responding!
