### ISSUE TITLE
WritingMode set to Rotate270 for column headers not rotated.

### ISSUE THREAD

**Issue by TartanBono** [ilich/MvcReportViewer#158]
Hi,

Great tool!

I have written a matrix report which has a numerous column headers where the WritingMode property has been set to Rotate270, makes it more readable, less scrolling lol. This works fine when executing/running the reports on the server during testing but when I try to view in the embedded MvcReportViewer the columns are not rotated??

Am I doing something wrong? Any ideas why the columns are not rotated when using the viewer...

Thanks
TB

**Comment by ilich** [comment]
It seems to be a problem with ReportViewer Control itself. MvcReportViewer is just a wrapper around this control. 

Check this:

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/64f4a8c6-2a5f-4137-beca-18e653ca60c8/problem-in-writing-mode-in-ssrs-2008-r2?forum=sqlreportingservices

http://forums.asp.net/t/1901981.aspx?ReportViewer+does+not+display+rotated+header+text+vertically

https://martinbrusevold.wordpress.com/2011/12/21/rotate-text-in-reportviewer-rdlc/
