### ISSUE TITLE
Using an array as a parameter when getting a FileStreamResult

### ISSUE THREAD

**Issue by daveshapiro** [ilich/MvcReportViewer#160]
I've successfully used arrays as part of my parameters in other cases where I'm using the HtmlHelper to render the reportviewer to the page, but I'm having difficulty trying to get this to run in the controller in order to export to Excel and send an email.

In my controller:

```C#
var report = this.Report(ReportFormat.Excel, model.ReportPath, model.ToKeyValuePairs());
```

And on my model:

```C#
public IEnumerable<KeyValuePair<string, object>> ToKeyValuePairs()
{
     return new List<KeyValuePair<string, object>>()
     {
           new KeyValuePair<string, object>("startDate", StartDate),
           new KeyValuePair<string, object>("endDate", EndDate),
           new KeyValuePair<string, object>("ids", Ids.ToArray())
     };
}
```

I've also tried concatenating ids into a comma separated list, but no matter what I always get:
`This report requires a default or user-defined value for the report parameter 'ids'. To run or subscribe to this report, you must provide a parameter value. (rsReportParameterValueNotSet)`

**Comment by ilich** [comment]
Thank you for the report. I fixed the problem. Use the latest repository snapshot to use the fix right now. 

The fix will be packages with MvcReportViewer 0.8.4

**Comment by daveshapiro** [comment]
Hi @ilich, still waiting for the 0.8.4 release.  Any idea when this will be available to nuget?

**Comment by ilich** [comment]
It is hard to say at the moment. I am maintaining the project on my free time. Unfortunately I do not have free time. I will fix few more issues, merge pull request and deploy once I have little bit of free time. Unfortunately this project is not related to my work.
