### ISSUE TITLE
External image not rendering on HTML report

### ISSUE THREAD

**Issue by hulahomer** [ilich/MvcReportViewer#164]
I have a report with an external image embedded in it, with a path to a known image at a http address. It looks like this in my RDL file:
`                    <Image Name="Image5">
                      <Source>External</Source>
                      <Value>=Fields!LogoPath.Value</Value>
                      <Sizing>FitProportional</Sizing>
                      <Style>
                        <Border>
                          <Style>None</Style>
                        </Border>
                      </Style>
                    </Image>`

This renders fine inside the report viewer, but when I want to get the report in HTML format like this (sample code, not my real code):
`            var parameters = new List<KeyValuePair<string, object>>();
            parameters.Add(new KeyValuePair<string, object>("ExampleParameter", "Testing"));

            var report = this.Report(ReportFormat.Html,
                "ReportName",
                parameters);`

The report that comes back from this has all the data except the image is not in the html. Inside the html I see the image tag looks like the following, where the height is set to 5px:

`<IMG onload="this.fitproportional=true;this.pv=0;this.ph=0;" HEIGHT="5px" SRC="http://localhost:52252/ReportServer?%2FReportName&rs%3ASessionID=4y1fuy554n3in345nkzp4p45&rs%3AFormat=HTML4.0&rs%3AImageID=c45646126df94faf860305bbc484c027"/>`

Even when I expand the image tag beyond the 5px height, there is still no image that shows.

Is this a limitation of using the HTML format, since if I use the MHTML export inside the ssrs viewer, it will render it with the image, but HTML is not an option for export in the build in viewer? Any help would be appreciated.

Update:
When I change the src link in the img above to not have the port 52252 on the link then my browser returns back the image to save, since the report server is not running on that port, only my dev build in visual studio is. Is there something updating the image link to include that port number when it shouldn't be there?

**Comment by ilich** [comment]
Your problem is related to Report Viewer Web Control. MvcReportViewer is just a wrapper around the control developed by Microsoft.

I hope http://stackoverflow.com/questions/15502186/embedded-images-in-ssrs-reports-not-displaying-permissions-issue will help you to solve the issue.
