### ISSUE TITLE
Blank iframe Loading

### ISSUE THREAD

**Issue by DanielCauser** [ilich/MvcReportViewer#180]
Hello, i've found a problem witch i can't seem to figure out.

I'm using reportviewer on MVC 4 application. I have a page  witch loads the reportviewer iframe via ajax. When I set the iframe to load in a div in my client hmtl, it takes a few moments with a blank iframe, until it loads the content of the report.

I'm trying to set jquery load and ready listeners to the iframe, so instead of the blank space it would show a loading gif until the iframe is ready. 

Any help ?!

**Comment by ilich** [comment]
Hello Daniel,

I am sorry for the late reply. I am busy with other projects, and do not have a lot of free time at the moment. I hope http://stackoverflow.com/questions/12267010/how-can-i-detect-whether-an-iframe-is-loaded will help you. For example,

```js
$(function(){
    $('#MainPopupIframe').on('load', function(){
        $(this).show();
        console.log('load the iframe')
    });

    $('#click').on('click', function(){
        $('#MainPopupIframe').attr('src', 'http://heera.it');    
    });
});
```
