### ISSUE TITLE
Blank iframe in local azure-report

### ISSUE THREAD

**Issue by dislappss** [ilich/MvcReportViewer#182]
Hello, I have a problem.
My local report appears in a normal way in my computer, but it stays blank when it is uploaded in the azure-host. 

Thank you for help.

---------------------------------------------------------
.cshtml:
@{
        var settings = new ControlSettings
            {
                UseCurrentAppDomainPermissionSet = true,
                ShowParameterPrompts = false,
                ShowFindControls = true,
                ShowToolBar = true,
                AsyncRendering = false,
                ZoomMode = ZoomMode.PageWidth,
                SizeToReportContent = false
            };            
    }

@Html.MvcReportViewerFluent("App_Data/Reports/articles.rdlc").LocalDataSource("data", Model.data).LocalDataSource("labels", Model.labels).ProcessingMode(ProcessingMode.Local).Attributes(new { Height = 900, Width = "100%", style = "border: none" }).ControlSettings(settings)
-------------------------------------------------------------------------------
Web.config:
.....
<appSettings>
    <add key="webpages:Version" value="2.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="PreserveLoginUrl" value="true" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />    
    <add key="MvcReportViewer.AspxViewer" value="~/MvcReportViewer.aspx" />
    <add key="MvcReportViewer.AspxViewerJavaScript" value="~/Scripts/MvcReportViewer.js" />
    <add key="MvcReportViewer.ErrorPage" value="~/MvcReportViewerErrorPage.html" />
    <add key="MvcReportViewer.ShowErrorPage" value="false" />    
    <add key="MvcReportViewer.LocalDataSourceProvider"   value="MvcReportViewer.SessionLocalDataSourceProvider, MvcReportViewer" />
......

<httpHandlers>
      <add path="*" verb="*" type="System.Web.HttpNotFoundHandler" />
      <add path="Reserved.ReportViewerWebControl.axd" verb="*" type="Microsoft.Reporting.WebForms.HttpHandler, Microsoft.ReportViewer.WebForms, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" validate="false" />
 <remove name="ReportViewerWebControlHandler" />
      <add name="ReportViewerWebControlHandler" preCondition="integratedMode" verb="*" path="Reserved.ReportViewerWebControl.axd" type="Microsoft.Reporting.WebForms.HttpHandler, Microsoft.ReportViewer.WebForms, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" />
.....

**Comment by icozma** [comment]
I had the same issue:    blank report, on a local instance of SSRS; 
the issue was that the application user did not had permissions to browse the report on SSRS.

**Comment by ilich** [comment]
Thank you, @icozma! It seems to be a problem with disk permissions. I have never tried to run this on Azure, but I experienced the same problem on a virtual server.

**Comment by mickeysuda** [comment]
I have same issue, just try to use the "\" in the path instead of "/", so instead of "App_Data/Reports/articles.rdlc", it should be "App_Data\Reports\articles.rdlc"
