### ISSUE TITLE
Not able to load the rdl file (Blank output)

### ISSUE THREAD

**Issue by gitsubash** [ilich/MvcReportViewer#183]
Hello,
I have generated the *.rdl file from SSRS and put the one in the App_data/Reports/MyReport.rdl.
On debug i found that the model object is getting data correctly from db and and also reflecting in model in LocalReports.cshtml with model.Result1

Used model is very simple as the one in given example:
`public class RDLViewModel
{
    public System.Data.DataTable Result1 { get; set; }
}` 

I have also set <add key="MvcReportViewer.ShowErrorPage" value="False" /> and not getting any errors.

`@using Microsoft.Reporting.WebForms;
@using MvcReportViewer;
@using MVCReportViwerApplication.Models;

@model RDLViewModel
@{
        ViewBag.Title = "LocalReports";

        var settings = new ControlSettings
        {
            UseCurrentAppDomainPermissionSet = true,
            EnableHyperlinks = true
    };
}

<h2>LocalReports</h2>

@Html.MvcReportViewerFluent("App_Data/Reports/MyReport.rdl").ProcessingMode(ProcessingMode.Local).LocalDataSource("Result1", Model.Result1).ControlSettings(settings).Attributes(new { Height = 900, Width = 900, style = "border: none" })`

As far my research rdl and rdlc file format are same except datasets element, so have the mvcreportviewer is tested with rdl or Am i making something wrong.

The output is blank without any errors, so I am stuck!!!

**Comment by tiesont** [comment]
_Take the below my opinion/suggestion only, as I am not a dev on this project:_

This project (at it's core) is nothing more than a wrapper around the WebForms ReportViewer control. ReportViewer will not load .rdl files locally with `ProcessingMode.Local`. You _might_ be able to use [Report.LoadReportDefinition](https://msdn.microsoft.com/en-us/library/ms252132.aspx) to load the file definition locally, but it will still be processed remotely. 

I also don't see that a Report object is ever used in this project, so it's probably not possible at the moment anyway.

It's worth noting that (since MVC is built on top of ASP.NET) you *can* mix WebForms and MVC in one project, so there's nothing stopping you from adding a WebForms page and using the ReportViewer directly.

**Comment by gitsubash** [comment]
@tiesont  thanks for your suggestions !!! Yes, I have added the reportviewer in webforms of mvc application but trying to attach the definition from rdl file and connect to my db to get dataset and fill the reportviewer wrapper class. 

Have you ever worked with rdl file and checked the diff. between rdl and rdlc? So, that I could get more insights on it.
Thanks, Subash

**Comment by tiesont** [comment]
You don't need a separate application. You can mix controller and views with WebForms (.aspx) pages within a single application, and even still use routing. 

The only thing that (somewhat) prevents you from doing so is if you're trying to mix VB.NET and C# - it takes a fair amount of kludging to make those work side-by-side.

I'm not sure what you mean by "call them using controller methods" - you can redirect to any URL from a controller action. You wouldn't return a WebForms page as an ActionResult, though, if that's what you're trying to do (it's possible, but why do that when a redirect works?).

**Comment by ilich** [comment]
Hello,

As I know, Microsoft Report Viewer cannot render SSRS RDL reports. You have to deploy then to your SSRS server or create a local reports in Visual Studio (*.rdlc). 

If you want to use SSRS then you should use Remote Processing mode. You can find sample code in the Example application I created for this project.

If it does not help then I'd suggest to check the following.

1. Make sure that you have all components setup on the server. Check **Intallation** part in the documentation (README.md)

2. Enable ASP.NET errors in Web.config. Set showErrorPage="true" and errorPage="" for your MvcReportViewer tag or change Application Settings if you use this approach
```xml
<add key="MvcReportViewer.ErrorPage" value="" />
<add key="MvcReportViewer.ShowErrorPage" value="True" />
```

If nothing help than take the source code from git, add it to the project and build it. 

Please let me know if you will find any issue in the code itself.


Thanks,
Ilya
