### ISSUE TITLE
Passing URL Parameters into the report

### ISSUE THREAD

**Issue by Logicaled** [ilich/MvcReportViewer#189]
Is it possible to accept parameter values from a url string to a hosted report on a mvc site, using this report viewer tool?

Thanks

**Comment by ilich** [comment]
First, you should create parameters in the report. Then you parse URL and add the parameters to ```Enumerable<KeyValuePair<string, object>>``` property on your model. The last step is to render your report using ```@Html.MvcReportViewer(string reportPath, IEnumerable<KeyValuePair<string, object>> reportParameters, object htmlAttributes)``` helper method or a similar method using accepting  ```Enumerable<KeyValuePair<string, object>>``` arument.
