### ISSUE TITLE
MvcReportViewer Browser issue

### ISSUE THREAD

**Issue by jeok70** [ilich/MvcReportViewer#191]
About MvcReportViewer supported Many Browser, 
The MvcReportViewer in google chrome firefox Safari Browser  click print button  Jump out download pdf file Message, But IE Browser Can not download pdf file so  print directly

The google chrome firefox Safari browser can be the same as IE browser Can not download pdf file so  print directly ?

**Comment by ilich** [comment]
Unfortunately it is not possible because MS Report Viewer control supports only IE. I have added print to PDF for Chrome and Firefox just to make the UX nicer.
