### ISSUE TITLE
SQL Server Reporting Services 2016

### ISSUE THREAD

**Issue by RamblingGeekUK** [ilich/MvcReportViewer#192]
Does this work with SQL Server Reporting Services 13.01601.5

Nothing is being rendered in my MVC app.  Just blank, no errors?   Do I need to install the 2012 bits?

**Comment by ilich** [comment]
The project uses Microsoft Report Viewer 2012 to render reports. Make sure it is installed on your server. https://www.microsoft.com/en-us/download/details.aspx?id=35747

Please make sure that your configuration in Web.config is correct. I haven't tested the library with the latest SSRS. I hope I will find time in the future to update it.
