### ISSUE TITLE
Slow Performance when using more than 1 Viewer on a page

### ISSUE THREAD

**Issue by nhaberl** [ilich/MvcReportViewer#196]
Hi,

Is there anything we can do here that the reports render faster … when using 12 iFrames (render over partial view) with dummy reports which render on server (local network) in under 10 ms it takes 20 seconds until all iFrames show the content.

Is the handler executed synchronously or any other bottleneck anywhere in the pipeline?

Would be great to get any help here, it’s such a great software!

**Comment by ilich** [comment]
You can try to set AsyncRendering  = True in report control settings. 

The library is a wrapper around ASP.NET Web Forms Report Viewer control. We just call the viewer for each request. ASP.NET Web Form application does not use async features internally.
