### ISSUE TITLE
Csv export for local reports

### ISSUE THREAD

**Issue by igor-moskvitin** [ilich/MvcReportViewer#206]
Hi! Is there any chance to add **export csv** for local reports (rdlc)?

**Comment by ilich** [comment]
Unfortunately it seems that ReportViewer does not support export to CSV in Local mode.

http://stackoverflow.com/questions/984617/how-to-configure-reportviewer-so-it-can-be-exported-csv-in-asp-net

It seems that ReportViewer should support CSV in Remote mode, but you will have to use SSRS.

https://technet.microsoft.com/en-us/library/cc627537(v=sql.100).aspx

**Comment by igor-moskvitin** [comment]
Anyway, thanks for nice tool!
