### ISSUE TITLE
Windows Authentication issue

### ISSUE THREAD

**Issue by hjrb** [ilich/MvcReportViewer#207]
Scenario: 
- ServerA: IIS with Windows Authentication enabled hosting my intranet web site with the MvcReportView 
- ServerB: Report Server with Windows Authentication enabled hosting the reports
When I run my WebSite on my local PC with my user account all works fine.
But when I deploy the WebSite to ServerA and try to access the reports from my PC I get the following error message:
"The access rights granted to the user domain\ServerA$ are not sufficient.+(rsAccessDenied)"
Obviously the requst to the report server does not forward the Windows authentication.
Could this be a double hop problem? http://www.sqlservercentral.com/articles/Double+Hop/76743/

**Comment by ilich** [comment]
I haven't experienced the issue myself. Most of the reports I developed were running inside Windows domain. We used Active Directory for authentication.

Please check you IIS App Domain user's permissions. I think this is the problem causing the error.
