### ISSUE TITLE
Get troubles on display when changed Website Server

### ISSUE THREAD

**Issue by Nnayl** [ilich/MvcReportViewer#208]
Hi,

I want to migrate my website from a Windows server 2012 with IIS 8.0 to a Windows server 2016 with 10.0 and I encounter some trouble with the display of my reports. (Report host by a reporting server on other machine)

Display look like this when website hosted by my personal computer IIS (windows 7 with IIS 7.0) or WS2012 :
![good display](https://cloud.githubusercontent.com/assets/11646183/25698138/f46c67ce-30bd-11e7-9898-420b549c5cfc.png)

Display look like this when website hosted by WS2016 :
![bad display](https://cloud.githubusercontent.com/assets/11646183/25698139/f471e9c4-30bd-11e7-916d-25c2aa287471.png)

I don’t understand what’s append !

Code : 
```c#
@{
        var settings = new ControlSettings
        {
            ShowParameterPrompts = true,
            ShowFindControls = false,
            KeepSessionAlive = false,
            AsyncRendering = false,
            SizeToReportContent = false,
            ShowPrintButton = false,
            ShowExportControls = false

    };
}

@Html.MvcReportViewerFluent(
             "/MyReport").Username("myUser")).Password(
             ("MyPassw")).Attributes(
             new { Height = 1500, Width = "100%", style = "border: none" }
        ).ControlSettings(settings)
```

MVC Website compiled with .net 4.5
.net 4.5 framework installed to all servers
Application pool CLN .net v4.030319 pipeline Classic on all IIS

Do you have some ideas ?

Thanks for your replies !

**Comment by Nnayl** [comment]
Hi,
I fixed the problem !

for a reason i not understanding, Mircrosoft.ReportViewer.* DLL in my BIN folder didn’t be use.
IIS use GAC DLL with version 13.0.1601.5, however my BIN DLL are version 13.0.1700.305.

I updated manually DLL in GAC and it work fine

**Comment by ilich** [comment]
Thank you for the update.
