### ISSUE TITLE
Can you refresh the report with new parameters?

### ISSUE THREAD

**Issue by deynq** [ilich/MvcReportViewer#214]
I'm trying to  show a report from SSRS with this code. 

@Html.MvcReportViewer(AppSettings.ReportServerPath , 
                new { ReportUser = "This User"}),
                new { width = 1700, height = 800, style = "border: none" })

The report is displayed. But can I modify the ReportUser parameter and pass it the viewer and refresh the report?

**Comment by ilich** [comment]
You should do create a report model on your page and pass parameter from the model to the HTML helper. The rendering is done on the server, so you need to do POST or GET request. MvcReportViewer does not provide client side API for that.
