### ISSUE TITLE
Can I use this with ASP.net core2.0 projects

### ISSUE THREAD

**Issue by wsrinivas** [ilich/MvcReportViewer#216]
Got a error saying that it was restored for package 4.6.1 instead of CoreApp=V2.0

**Comment by wsrinivas** [comment]
Will is also work with RDL's created on 2008 database in mind?

**Comment by ilich** [comment]
Unfortunately this project will not work on ASP.NET Core because it requires ASP.NET Web Forms to run the reader. Web Forms are only available for .NET Framework.
