### ISSUE TITLE
HTTP Error 400. The size of the request headers is too long.

### ISSUE THREAD

**Issue by vivekcpatel** [ilich/MvcReportViewer#219]
Hi, I updated the nuget package on my project. I also set the KeepSessionAlive="true". But I am still getting this error. I have attached the sample request. Is there a limit somewhere that i could change to get passed this error?
[Report Viewer Request.txt](https://github.com/ilich/MvcReportViewer/files/1769872/Report.Viewer.Request.txt)

**Comment by ilich** [comment]
It seems that IIS does not like HTTP header you're sending. e.g. you may send very large cookie, etc. Please check https://forums.asp.net/t/2027961.aspx?HTTP+400+The+size+of+the+request+headers+is+too+long+ recommendations. I hope they will help in your case.

**Comment by vivekcpatel** [comment]
It was because **Referer** was added to the request. In my case the whole report parameters request was added as to this Referer tag and it was making the request too long. I removed the referer from the request and it worked. In order to remove this you can add 
`<meta name="referrer" content="no-referrer" />`
to the head tag in your .aspx page and it should work after.
