### ISSUE TITLE
.Net 4.7 problem

### ISSUE THREAD

**Issue by SergioKastro** [ilich/MvcReportViewer#224]
Hi:

I have a question. I have recently update my solution where I am using the MvcReportViewer to .Net 4.7 and since then the reports are not anymore accesible using the MvcReportViewer. The error that I am getting is the following:
   Microsoft.Reporting.WebForms.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection+MissingEndpointException: The+attempt+to+connect+to+the+report+server+failed.++Check+your+connection+information+and+that+the+report+server+is+a+compatible+version.

I am gessing the problem is MvcReportViewer is not working with that framework.
 Can someone confirm this?
 Do you know how to solve this problem?

Thanks for your help.

Regards;
Sergio

**Comment by ilich** [comment]
This is SSRS server issue. Report Viewer Web control cannot connect your SSRS server. Please check the configuration. It might be SSRS authentication issue on the server or networking problem. The exception is raised by Report Viewer web control itself.

**Comment by SergioKastro** [comment]
Yes, you were right. We also updated to the latest MvcReportViewer and it added a new entry in our web config and we didnt noticed.

Problem now it is solved.

Thank you for your help
