### ISSUE TITLE
Could not load file or assembly Microsoft.ReportViewer.Common, Version=11.0.0.0

### ISSUE THREAD

**Issue by kcruzado** [ilich/MvcReportViewer#23]
It works locally, but when I deploy to server I get the following error when trying to view a report. 
Could not load file or assembly 'Microsoft.ReportViewer.Common, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified. 
![error](https://f.cloud.github.com/assets/611297/2411898/80a98774-aacc-11e3-924b-9b094533e047.png)

**Comment by aneelponnada** [comment]
> kcruzado,
> 
> Thank you!
> 
> baodinh,
> 
> Go to http://www.microsoft.com/en-us/download/details.aspx?id=35747 (Developer Tools
> MICROSOFT® REPORT VIEWER 2012 RUNTIME). Download the viewer runtime and SQL Server System CLR Types (see Related Resources at the bottom of the page). Install these to your server. I think it should fix the issue.

Hi,

This worked for me. Thank you so much for your help.
