### ISSUE TITLE
Assembly 'MvcReportViewer' which has a higher version than referenced assembly 'System.Web.Mvc'

### ISSUE THREAD

**Issue by hayurahiza** [ilich/MvcReportViewer#3]
Hi, 

The test project works fine but I have problem to intergrate the MvcReportViewer to my existing project.

Compiler Error Message: CS1705: Assembly 'MvcReportViewer, Version=0.2.5072.5704, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by prashanth866** [comment]
Hi,
I would be interested in know how to achieve what you told above(Using mvcreportviewer in ASP.NET MVC3 ).I cannot understand what you mean by " replace ASP.NET MVC reverence from 4 to 3 and rebuild it".It would be great if u can guide me with the steps to do that. I searched everywhere but couldn't find any resource.

**Comment by ilich** [comment]
Hi,

1. Create new class library and add MVC3 references there and ASP.NET Report Viewer Control
2. Add https://github.com/ilich/MvcReportViewer/tree/master/MvcReportViewer code to the project
3. Try to build. I cannot guarantee that it will work because ASP.NET MVC 5 API is different from MVC 3.
