### ISSUE TITLE
Print button and date picker in SSRS reports for non-IE browsers (Chrome, Firefox, etc.)

### ISSUE THREAD

**Issue by rarrrrr** [ilich/MvcReportViewer#39]
With non-IE browsers such as Google Chrome and Firefox, the print button is missing and the date picker is not displayed as a control. This is a limitation in the underlying ReportViewer control as highlighted on a CodeProject article here: http://www.codeproject.com/Articles/504567/Print-button-and-date-picker-in-SSRS-reports-for-n

Extending this project with the work around identified in the article will make it more useful for non-IE browsers.

**Comment by darius200-rbg** [comment]
hi, i am having this issue of calendar control not showing for a report. I got the latest version of MvcReportViewer from NuGet in Visual Studio 2022. The calendar control does not show in Edge, nor Chrome. Is there a solution?
