### ISSUE TITLE
Scroll Bar issues in ie 11, works good in other browser and older IE.

### ISSUE THREAD

**Issue by savarirajpeter** [ilich/MvcReportViewer#52]
Scroll bar appears perfectly well in IE 10, chrome, IE 8, where as it does not appear well in IE 11. 
I have added the image for your reference,

I have the following setting,

   ControlSettings ReportSettings = new ControlSettings();
 ReportSettings.AsyncRendering = true;
   ReportSettings.Width = new Unit("100%");
    ReportSettings.Height = new Unit("440px");
ReportSettings.SizeToReportContent = false;

@Html.MvcReportViewerFluent(Model.ReportName).ControlSettings(ReportSettings).Attributes(new { @class = "form-control", style = "width : 100% ; height: 480px ;  overflow : hidden; border: none" })
![untitled](https://cloud.githubusercontent.com/assets/9655984/5142158/2c5b324e-71a5-11e4-8283-ef06df7c35f1.png)

**Comment by Lfwinster** [comment]
This might be a fix: there is a css attribute in the reportviewer div called overflow:auto, remove that and add overflow-x:visible can fix the problem. you don't have to add overflow-x:visible to fix it. just remove the auto.

**Comment by ravirambles** [comment]
Thanks Lfwinster this is the only fix that is actually working for me.

**Comment by ghost** [comment]
I am able to resolve this by adding the inline style

_:-ms-fullscreen, :root #VisibleReportContentreportViewer_ctl09 {
        position: absolute;
        display: inline-block !important;
    }

**Comment by andylop04** [comment]
I only registered for say: VIJAYASHANKAR: YOU ARE AWESOME! Thanks for your solution.

**Comment by hardikjoshi51** [comment]
@VIJAYASHANKAR  where should I add this style?

**Comment by ghost** [comment]
Please go through this blog https://www.c-sharpcorner.com/blogs/how-to-display-vertical-scroll-bar-for-asp-net-report-viewermvcreportviewer-in-ie11

**Comment by rajatlanta** [comment]
VIJAYASHANKAR,
                            The above link is not working. Can you please help with where to add the code you mentioned.

**Comment by ghost** [comment]
The MVCReportViewer control internally using Asp.net ReportViewer Control to render the report in Asp.net MVC Apps, during validation found the report appears with the vertical scroll bar in IE 10, chrome, IE 8, whereas it does not appear well in IE 11. And most of the sites they have mentioned it's a known issue, however, this can be resolved by just adding a CSS to your report container as like below   
 
_:-ms-fullscreen, :root #VisibleReportContentreportViewer_ctl09 {  
position: absolute;  
display: inline-block !important;  
}   
Ensure the above line has to added on the page where you are referring the report viewer controller in the page style block
