### ISSUE TITLE
HTTP Error 500.23 - Internal Server Error

### ISSUE THREAD

**Issue by travisneale** [ilich/MvcReportViewer#56]
Hi Ilich!  First time trying your product!  I am receiving the following error:
"An ASP.NET setting has been detected that does not apply in Integrated managed pipeline mode."
"•This application defines configuration in the system.web/httpHandlers section."
It's an Azure website, .NET 4.5 in Integrated pipeline mode.  Am I missing something?
Thanks,
 Travis

**Comment by ilich** [comment]
Hi. I have never worked with Azure web-sites. I usually use this recommendation to run my sites locally: http://stackoverflow.com/questions/4209999/an-asp-net-setting-has-been-detected-that-does-not-apply-in-integrated-managed-p

It should be enough to set configuration/system.webServer/validation/@validateIntegratedModeConfiguration="false"

Please add you notes here when you will find the fix.

Thanks,
Ilya

**Comment by npavgi** [comment]
See if this helps in any way -
http://stackoverflow.com/questions/7347897/internal-server-error-with-httphandlers-section-of-web-config

**Comment by travisneale** [comment]
Thank you both!  Yes, simply turning off configuration validation gets me past the error.
In web config.
```
 <configuration>
        <system.webServer>
            <validation validateIntegratedModeConfiguration="false"/>
        </system.webServer>
    </configuration>
```
I guess I should have googled further!  
Thanks again.  Looking forward to playing with this.
-Travis
