### ISSUE TITLE
This will allow MvcReportViewer to work with version 12.0.0.0 of Microsoft.ReportViewer

### ISSUE THREAD

**Issue by livesoftware** [ilich/MvcReportViewer#57]
<dependentAssembly>
          <assemblyIdentity name="Microsoft.ReportViewer.DataVisualization" culture="neutral" publicKeyToken="89845dcd8080cc91" />
          <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
        </dependentAssembly>
      </assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.ReportViewer.Common" culture="neutral" publicKeyToken="89845dcd8080cc91" />
          <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
        </dependentAssembly>
      </assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.ReportViewer.WebForms" culture="neutral" publicKeyToken="89845dcd8080cc91" />
          <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
        </dependentAssembly>
      </assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.ReportViewer.ProcessingObjectModel" culture="neutral" publicKeyToken="89845dcd8080cc91" />
          <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
        </dependentAssembly>
      </assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.SqlServer.Types" culture="neutral" publicKeyToken="89845dcd8080cc91" />
          <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
        </dependentAssembly>
      </assemblyBinding>

**Comment by ilich** [comment]
Thank you for the information. I have added this note to the Wiki

https://github.com/ilich/MvcReportViewer/wiki/Allow-MvcReportViewer-to-work-with-version-12.0.0.0-of-Microsoft.ReportViewer
