### ISSUE TITLE
Param Visibility (Partial) - Enhancement

### ISSUE THREAD

**Issue by farhaniqbal** [ilich/MvcReportViewer#59]
While working in ASP.NET, we had the option of assigning values to @params and hide them (using following code)
List<ReportParameter> userKeyParam = new List<ReportParameter>(); 
userKeyParam.Add(new ReportParameter("paramName", "paramVal", false)); //false represent param visibility

Now in MvcReportViewer, ReportParameter (which is KeyValuePair<string, object>) does not have visible property. It would be really handy when user wants to assign sensitive "paramVal" from code, and let the user allow to enter generic param val.

**Comment by ilich** [comment]
I have implemented this feature. It will be available in the next NuGet package.
