### ISSUE TITLE
Conflict Umbraco + IIS7.5

### ISSUE THREAD

**Issue by arturosoler** [ilich/MvcReportViewer#60]
I am developing a project with the Umbraco CMS and I installed mvcreportviewer.
In my development machine (IISExpress) everything works fine.
But when I moved to IIS7.5 (W2008R2) or IIS8 (W2012) an  RuntimeBinderException occurs.
This error disappears by deleting mvcReportViewer.dll.
Any suggestions?
Although I do not think it serves much the exception information is:
    Tipo de excepción: RuntimeBinderException 
    Mensaje de la excepción: 'Umbraco.Web.Models.DynamicPublishedContentList' no contiene una definición para 'Count'.
   en CallSite.Target(Closure , CallSite , Object )
   en System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   en ASP._Page_Views_Partials_BloqueComunInicio_cshtml.Execute() en e:\Inetpub\Aplicaciones\ASOC_GENERAL.NET\u01\Views\Partials\BloqueComunInicio.cshtml:línea 10
   en System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   en System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   en System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   en Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   en System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   en ASP._Page_Views_InicioPrincipal_cshtml.Execute() en e:\Inetpub\Aplicaciones\ASOC_GENERAL.NET\u01\Views\InicioPrincipal.cshtml:línea 6
   en System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   en System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   en System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   en Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   en System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   en System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<InvokeActionResultWithFilters>b__17()
   en System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   en System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   en System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)
   en System.Web.Mvc.Controller.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   en System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   en System.Web.Mvc.MvcHandler.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by ilich** [comment]
Hello. Unfortunately I do not have in-depth experience with Umbraco. I cannot find MvcReportViewer calls in the stack trace. I'd recommend you to setup IIS 7.5/8 locally and debug Umbraco. It is open source. You can download the code, build it and run in a debugger.

Please let me know if you will find what the issue it. I'd like to add the solution to project's wiki.

Sincerely,
Ilya

**Comment by adamknudsen** [comment]
For a first step, consider putting exception handling and logging in
application start.  Most likely there is a name or dependency conflict that
is throwing an exception at startup but not killing the app.  This
exception has the appearance of an exception that is a side effect of an
assembly that did not load.  Maybe an assembly with extension methods?

**Comment by arturosoler** [comment]
Okey, I think I have a machine running IIS 7.5, W7 and VS10 where I can do these tests. It will take a few days / weeks because it is not a critical problem. I have curiosity and MVCreportviewer is a good tool to have in the box.

**Comment by ilich** [comment]
I think you should download MvcReportViewer source code and comment everything. Then you build it and deploy to Umbraco. Check that you Umbraco website  works. Then you can uncomment MvcReportViewer piece by piece till Umbraco fails. I think it might be one of they to find out what the compatibility issue is.

**Comment by arturosoler** [comment]
Yes. I like more this method. Debug all startup errors is desperate, and
view the code will be instructive. I do shortly (days).

2015-01-19 20:41 GMT+01:00 Ilya Verbitskiy <notifications@github.com>:

**Comment by arturosoler** [comment]
Solved! The whole problem was in DLL version conflicts.
Over breakfast on Sunday, I found this article that gave me the hint: http://blog.bartdemeyer.be/2013/01/the-hard-search-for-missing-extension-methods-in-umbraco-4-7- 0 /
Finally I installed the ReportViewer 2012 runtimes to IIS 7.5 and updated Microsoft ASP.NET MVC version 4 4.0.40804 at the VS project.
