### ISSUE TITLE
mvcreportviewer version is higher than specified

### ISSUE THREAD

**Issue by Sunilkattamuri** [ilich/MvcReportViewer#62]
I am getting the below error when i added the nuget to my solution.
MvcReportViewer, Version=0.5.5456.40272, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

However i have given the below entry in my web.config though there is no luck.

<dependentAssembly>
        <add assembly="System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
        <bindingRedirect oldVersion="4.0.0.0-4.0.0.1" newVersion="4.0.0.1"/>
      </dependentAssembly>

Please suggest!!

Thank you,

**Comment by ilich** [comment]
You have to update you ASP.NET MVC or download MvcReportViewer source code, reference you ASP.NET MVC assembly and build it.

**Comment by Sunilkattamuri** [comment]
to which version i  have to update.I am using MVC 4 already.

**Comment by ilich** [comment]
There are a few versions on ASP.NET MVC: http://www.nuget.org/packages/Microsoft.AspNet.Mvc/

I'd try ASP.NET MVC 4.4.
