### ISSUE TITLE
Cant Get the Example to work

### ISSUE THREAD

**Issue by j-tee** [ilich/MvcReportViewer#65]
I need help here. Just simply cant get the example to work on my machine. All I get is the message 
                   
    "@Html.MvcReportViewer(
        "/TestReports/TestReport",
        new { Parameter1 = "Hello World!", Parameter2 = DateTime.Now, Parameter3 = 12345, Parameter4 = DateTime.UtcNow },
        new { Height = 900, Width = 900, style = "border: none" })" and  "Service unavailable!
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later. "

**Comment by ilich** [comment]
You should set MvcReportViewer.ShowErrorPage to False in your Web.config. I think you SSRS server is not running or you are using wrong report path or credentials.

**Comment by Jeelani786** [comment]
I have the same issue. don't know what is going wrong can you please check my code.

Home.cshtml:
@Html.MvcReportViewerFluent("/GFIReports/TestReports/TestReportWL")
.Attributes(new { Height = 900, Width = 900, style = "border: none" })

**Comment by ilich** [comment]
Your code looks good. Something is wrong with your server setup. You should set MvcReportViewer.ShowErrorPage to False in your Web.config. I think you SSRS server is not running or you are using wrong report path or credentials.
