### ISSUE TITLE
MvcReportViewer control ID is missing

### ISSUE THREAD

**Issue by wboevink** [ilich/MvcReportViewer#68]
Running the code below I get an error: MvcReportViewer control ID is missing

return this.Report(ReportFormat.PDF, "/Naviva/Acceptatie/Reports/Sjablonen/Factuur", new { factuurnummer = nummer });

It's a remote report

**Comment by wboevink** [comment]
Version MvcReportViewer 0.5.2, which hasn't the localreport option, works with the code above.

**Comment by ilich** [comment]
Thank you for the report. I have already fixed the issue in the repository. You can download the code and use your custom build. I am going to release NuGet package in a day or two.

**Comment by ilich** [comment]
I have released v.0.6.2. You can test the fix now.

**Comment by wboevink** [comment]
Hi IIya,

I want to say thanks for the quick response and fix. I'll test the fix tomorrow.

Best regards,

Wouter
