### ISSUE TITLE
MvcReportViewer control ID is missing

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [ilich/MvcReportViewer#70]
Hi,

I'm getting an error similar to https://github.com/ilich/MvcReportViewer/issues/68

I get a control ID error when I try and run the following code;
```
string ReportName = "Reports/DailyReport.rdl"; 
DateTime d = new DateTime(2015,03,31);

return this.Report(
                    ReportFormat.PDF,
                    ReportName,
                    new { PortfolioID = 1, ValueDate = d},
                    ProcessingMode.Local);
```

Though my difference is I can't get it to work on 0.5.2 so I may be doing something wrong?

**Comment by ilich** [comment]
Hi,

You will not be able to use it on 0.5.2. You have to upgrade to 0.6.2.

**Comment by ChrisAllisonMalta** [comment]
Sorry I wasn't clear, I couldn't get it to work on 0.6.2, I tried 0.5.2 but that didn't work either

**Comment by ilich** [comment]
Are you sure you provide data source for your local report? For example,

<code>
 return this.Report(
                    ReportFormat.PDF,
                    "App_Data/Reports/Products.rdlc",
                    new { Parameter1 = "Test", Parameter2 = 123 },
                    ProcessingMode.Local,
                    new Dictionary<string, DataTable>
                    {
                        { "Products", GetProducts() },
                        { "Cities", GetCities() }
                    });
</code>

What is your error message? Could you send me a screenshot via http://screencast.com/ or something similar?

**Comment by ilich** [comment]
I was able to recreate the issue. I am going to fix it. Thank you for the report.

**Comment by ilich** [comment]
The issue has been fixed. Please install v0.6.3 and test your application.
