### ISSUE TITLE
How to use external image to show at ReportViewer

### ISSUE THREAD

**Issue by syaung** [ilich/MvcReportViewer#74]
I want to use external image with file path from report Param and Datasource at ReportViewer.
I don't know how to do it.
Please explain how to do it.

**Comment by ilich** [comment]
Hello. This is more the question about using SSRS, rather then the wrapper. I have never done it myself. I think toy can should start with https://technet.microsoft.com/en-us/library/dd220527.aspx article. Please let me know if you think that something should be enhanced in the wrapper to support report images.

**Comment by ilich** [comment]
Another useful article. https://technet.microsoft.com/en-us/library/dd239319.aspx

**Comment by syaung** [comment]
Now, I can view external photo with file path at ReportViewer.
Yes, Thanks for your help.
