### ISSUE TITLE
KeyNotFoundException: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by mkamoski** [ilich/MvcReportViewer#78]
Dear MvcReportViewer Experts -- 

I am not sure if this is an MvcReportViewer issue or not, so I am just guessing that it is, or that you can help in some way to get me un-blocked.

Please help. I am getting the dreaded "given key was not present" error on my SSRS report. This does happen after I deploy to a server that is protected by SiteMinder. This does NOT happen when running the report from VS 2013 in a Reporting project. This does NOT happen when running in VS debug mode in an MVC app that consumes the report. This does NOT happen when I run the report directly from a browser, passing in the correct query string, etc. This does NOT happen for all reports-- only for some of them. The report server and db server are the same in all cases. Do you have any ideas or suggestions or guesses? Is there a setting that I put into the MvcReportViewer declaration that will help get around this issue?

Please advise. 

Thanks. 

-- Mark Kamoski 

Server Error in '/MyCustomMvcSite' Application.

The given key was not present in the dictionary. 

  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

Source Error: 

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Generic.Dictionary`2.get_Item(TKey key) +14634191
   Microsoft.Reporting.WebForms.ParametersArea.RenderOneParameter(HtmlTextWriter writer, BaseParameterInputControl control) +266
   Microsoft.Reporting.WebForms.ParametersArea.RenderParameterControls(HtmlTextWriter writer) +830
   Microsoft.Reporting.WebForms.ParametersArea.RenderChildren(HtmlTextWriter writer) +782
   Microsoft.Reporting.WebForms.ParametersArea.Render(HtmlTextWriter writer) +302
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +150
   Microsoft.Reporting.WebForms.ReportViewer.RenderTopLevelUpdatePanelContents(HtmlTextWriter writer) +1797
   Microsoft.Reporting.WebForms.DelegatedRenderingControl.Render(HtmlTextWriter writer) +26
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +150
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +249
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +150
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +249
   System.Web.UI.UpdatePanel.RenderChildren(HtmlTextWriter writer) +355
   System.Web.UI.UpdatePanel.Render(HtmlTextWriter writer) +110
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +150
   Microsoft.Reporting.WebForms.ReportViewer.Render(HtmlTextWriter writer) +557
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +150
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +249
   System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer) +395
   System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) +49
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +150
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +249
   System.Web.UI.Page.Render(HtmlTextWriter writer) +40
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +150
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +5363

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34249

**Comment by ilich** [comment]
I have never used SiteMinder, and do not know what it is doing under hood. I can only guess, that it corrupts MvcReportViewer URL passed to the iframe. I'd recomment to

1. Use MvcReportViewer with encryption parameters or without (<add key="MvcReportViewer.EncryptParameters" value="False" /> in web.config)

2. Try to pass parameters using GET and POST methods (use Method(FormMethod method) in Fluent interface)

3. Get the source code, change report viewer and track what is missing in the URL. Your starting point might be https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewer/MvcReportViewer.aspx.cs
