### ISSUE TITLE
Error:  Check your connection information and that the report server is a compatible version

### ISSUE THREAD

**Issue by mkamoski** [ilich/MvcReportViewer#79]
Please help.
I just upgraded to MvcReportViewer 0.6.3.
Now reports that previously worked under 0.6.0 do not run and throw an error, detailed below.
The reports still run when in my VS 2013 reporting project.
The reports still run when I run locally on my dev machine in my VS 2013 MVC app.
After I deploy to the server, I get the error.
Is there any code that I need to change?
Is there a specific version of the report server that I need?
Do I need to rollback to a different version and, if yes, then how do I do that with NuGet?
How can I fix this?
Please help.
Thanks.
-- Mark Kamoski

ErrorDetails_BEGIN

errorType='Microsoft.Reporting.WebForms.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection+MissingEndpointException'
error='The attempt to connect to the report server failed.  Check your connection information and that the report server is a compatible version.'
ErrorDetails_END

SampleCode_BEGIN

@using MvcReportViewer;
@{
	ViewBag.Title = "MyReport";
}

@Html.MvcReportViewer(
	"/MyRoot/MyApp/MyReportV12",
	null,
	new {Height = 500, Width = 1000, style = "border: 1px solid lightgray;", keepsessionalive = "true"})

SampleCode_END

**Comment by ilich** [comment]
Report Viewer control uses Report Viewer for Web Forms v11.0. There might be compatibility issue with the controls installed on your server. I'd recommend you to install Microsoft Report Viewer 2012 Runtime (https://www.microsoft.com/en-us/download/details.aspx?id=35747). I know that this suggestion helped to others in the past.

If it won't help please create sample ASP.NET Web Forms application and try to run it on the server. Once it is working you will have an idea what is the configuration difference between you computer and the server.

**Comment by mkamoski** [comment]
Ilich -- 

I appreciate the response. but I beg your further help.

Is there any way to interrogate the report server to discover its Report Viewer version? Via a browser? Via a service call? Otherwise?

Regardless, since I do not have any control over the server, and I cannot change what is installed there, and I need to work with what is there now, I think I may have to downgrade the MvcReportViewer version in my app.

How can I downgrade the MvcReportViewer version? Via NuGet? Manually? Other options?

Please advise.

Thanks.

-- Mark Kamoski
