### ISSUE TITLE
Reference controls Toolbar methods directly

### ISSUE THREAD

**Issue by CanuckScott** [ilich/MvcReportViewer#82]
Firstly, thank you for the project.  Simple to install and lovely to be able to use the control seamlessly in mvc.

We have been tasked with replacing the toolbar functionality (zoom, next page, search, etc) with our own custom buttons.  As a result we specify the control setting "ShowToolBar = false" and have <buttons> on our form.  I had expected to be able set the report viewer's properties such as CurrentPage and ZoomPercent as well as call functions like PerformBack and Find.  Is this possible via your project?

Thank you again for your time on this.

**Comment by ilich** [comment]
Unfortunately it is not possible at the moment. The wrapper creates an iframe which hosts Report Viewer Control. I think what we need to do to create a JavaScript API which then will be used from client code. Could you create the list of functions you are using? Do you think JavaScript will work well in this case? Please provide your vision how it should work in ASP.NET MVC world.

**Comment by ilich** [comment]
I am closing it for now. Please reopen the ticket when you will be able to  provide more information about your idea.
