### ISSUE TITLE
Send parameters/data from Controller

### ISSUE THREAD

**Issue by arrudaw** [ilich/MvcReportViewer#83]
Thanks for the great job !
I need to view the report on the screen as the local report example , but I need send the data ( datasource / dataset / parameters) from the controller.
In our example, the parameters are passed on view using html helper and fill the dataset from controller. Not show how can pass parameters.

Is it possible ? How can I do? Do you have an example ?

Thanks in an advanced.

**Comment by ilich** [comment]
Yes, it should be possible. Please check Local Reports example in the sample application.

https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Controllers/HomeController.cs (line 112)

https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/LocalReports.cshtml

You will have to use Fluent interface to do this.

```
 @Html.MvcReportViewerFluent("App_Data/Reports/Cities.rdlc")
         .ProcessingMode(ProcessingMode.Local)
         .Method(FormMethod.Post)
         .LocalDataSource("Cities", Model.FilteredCities)
         .Attributes(new { Height = 900, Width = 900, style = "border: none" })
```

**Comment by morales-franco** [comment]
Hi ! I have a question the code;
 @Html.MvcReportViewerFluent("App_Data/Reports/Cities.rdlc")
         .ProcessingMode(ProcessingMode.Local)
         .Method(FormMethod.Post)
         .LocalDataSource("Cities", Model.FilteredCities)
         .Attributes(new { Height = 900, Width = 900, style = "border: none" })

Set LocalDataSource with "Cities" (dataSet's name) and Model.FilteredCities but Model.FilteredCities is a string not a dataTable, I have not override that support LocalDataSource(string, string).

I need send the data (List<Objetc> or datatable) from controller to the report
Is it possible ? How can I do? Do you have an example ?
Thanks in an advanced.

**Comment by morales-franco** [comment]
This is my code: 

In controller:
public ActionResult  ListReport()
        {
            LocalReportsModel model = new LocalReportsModel();
            model.Data= this.GetDataTable(); // mode.Data is DataTable type
            return View(model);
        }


In view:
@Html.MvcReportViewerFluent("Reports/ListReport.rdlc").ProcessingMode(ProcessingMode.Local).Method(FormMethod.Post).LocalDataSource("Mesas", Model.Data).Attributes(new { Height = 900, Width = "100%", style = "border: none;background-color:white;" })

**Mesas is dataSet's name

**Comment by ecosme8** [comment]
Hello Franco,

This is a code that I'm using right now and it works perfectly. What I do is create a class LocalReportsModel that has 2 DataTable Orders and Items. The function GetOrderItemsForOrderReport retuns a LocalReportsModel and fills the Datatable that you want, then you just return the model to the view and you use @Model.Orders which is the datatable filled with the data. Hope this works for you,

Controller:

[HttpPost]
public ActionResult OrderReport(string orderNumber)
        {
            LocalReportsModel model = OrderProvider.GetOrderItemsForOrderReport(orderNumber);

            TempData["ViewReport"] = true;

            return View(model);
        }

LocalReportsModel class:

public class LocalReportsModel
    {
        public DataTable Orders { get; set; }

        public DataTable Items { get; set; }
    }


GetOrderItemsForOrderReport Function:

public LocalReportsModel GetOrderForOrderReport(string orderNumber)
        {
            LocalReportsModel model = new LocalReportsModel();

string strSql = "SELECT O.SHIPMENT_ID, O.PURCHASE_ORDER_NUMBER, O.RELEASE_NUMBER, O.CHANGE_ORDER_SEQUENCE_NUMBER, ";
 strSql += "A.CODE_DESCRIPTION AS REFERENCE_IDENTIFICATION_QUALIFIER, O.REFERENCE_IDENTIFICATION, ";
strSql += "I.PRODUCT_SERVICE_ID_01, I.PRODUCT_SERVICE_ID_03, I.DESCRIPTION, I.NUMBER_OF_UNITS_SHIPPED, ";
strSql += "B.CODE_DESCRIPTION AS DATE_TIME_QUALIFIER, O.DATE_01, O.DATE_02 FROM dbo.ORDER_DETAIL O ";
strSql += "LEFT JOIN CODE_DESCRIPTIONS A ON O.REFERENCE_IDENTIFICATION_QUALIFIER = A.CODE ";
strSql += "LEFT JOIN CODE_DESCRIPTIONS B ON O.DATE_TIME_QUALIFIER = B.CODE ";
strSql += "INNER JOIN ITEM_DETAIL I ON O.PURCHASE_ORDER_NUMBER = I.ORDER_REF ";
strSql += "WHERE (I.ORDER_REF = @orderNumber OR @orderNumber = '') ";

var connectionString =
ConfigurationManager.ConnectionStrings["TransactionsDBEntities"].ConnectionString;
            
using (var connection = new SqlConnection(connectionString))
            {
                // GET ORDER DATATABLE
                using (var command = connection.CreateCommand())
                {
                    command.CommandText = strSql;
                    command.Parameters.Add("@orderNumber", SqlDbType.NVarChar);
                    command.Parameters["@orderNumber"].Value = orderNumber;

                    using (var adapter = new SqlDataAdapter(command))
                    {
                        var table = new DataTable();
                        adapter.Fill(table);
                        model.Orders = table;
                    }
                }
            }

            return model;
        }


And in the View:

@Html.MvcReportViewerFluent("App_Data/Reports/OrderReport.rdlc").ProcessingMode(ProcessingMode.Local).Attributes(
new { Height = 1000, Width = 1000, style = "border: none" }).Method(
FormMethod.Post).LocalDataSource(
"ReportDataset", @Model.Orders).ControlSettings(
 settings)

**Comment by ecosme8** [comment]
Hello Franco,

This is a code that I'm using right now and it works perfectly. What I do is create a class LocalReportsModel that has 2 DataTable Orders and Items. The function GetOrderItemsForOrderReport retuns a LocalReportsModel and fills the Datatable that you want, then you just return the model to the view and you use @Model.Orders which is the datatable filled with the data. Hope this works for you,

Controller:

[HttpPost]
public ActionResult OrderReport(string orderNumber)
        {
            LocalReportsModel model = OrderProvider.GetOrderItemsForOrderReport(orderNumber);

            TempData["ViewReport"] = true;

            return View(model);
        }

LocalReportsModel class:

public class LocalReportsModel
    {
        public DataTable Orders { get; set; }

        public DataTable Items { get; set; }
    }


GetOrderItemsForOrderReport Function:

public LocalReportsModel GetOrderForOrderReport(string orderNumber)
        {
            LocalReportsModel model = new LocalReportsModel();

string strSql = "SELECT O.SHIPMENT_ID, O.PURCHASE_ORDER_NUMBER, O.RELEASE_NUMBER, O.CHANGE_ORDER_SEQUENCE_NUMBER, ";
 strSql += "A.CODE_DESCRIPTION AS REFERENCE_IDENTIFICATION_QUALIFIER, O.REFERENCE_IDENTIFICATION, ";
strSql += "I.PRODUCT_SERVICE_ID_01, I.PRODUCT_SERVICE_ID_03, I.DESCRIPTION, I.NUMBER_OF_UNITS_SHIPPED, ";
strSql += "B.CODE_DESCRIPTION AS DATE_TIME_QUALIFIER, O.DATE_01, O.DATE_02 FROM dbo.ORDER_DETAIL O ";
strSql += "LEFT JOIN CODE_DESCRIPTIONS A ON O.REFERENCE_IDENTIFICATION_QUALIFIER = A.CODE ";
strSql += "LEFT JOIN CODE_DESCRIPTIONS B ON O.DATE_TIME_QUALIFIER = B.CODE ";
strSql += "INNER JOIN ITEM_DETAIL I ON O.PURCHASE_ORDER_NUMBER = I.ORDER_REF ";
strSql += "WHERE (I.ORDER_REF = @orderNumber OR @orderNumber = '') ";

var connectionString =
ConfigurationManager.ConnectionStrings["TransactionsDBEntities"].ConnectionString;
            
using (var connection = new SqlConnection(connectionString))
            {
                // GET ORDER DATATABLE
                using (var command = connection.CreateCommand())
                {
                    command.CommandText = strSql;
                    command.Parameters.Add("@orderNumber", SqlDbType.NVarChar);
                    command.Parameters["@orderNumber"].Value = orderNumber;

                    using (var adapter = new SqlDataAdapter(command))
                    {
                        var table = new DataTable();
                        adapter.Fill(table);
                        model.Orders = table;
                    }
                }
            }

            return model;
        }


And in the View:

@Html.MvcReportViewerFluent("App_Data/Reports/OrderReport.rdlc").ProcessingMode(ProcessingMode.Local).Attributes(
new { Height = 1000, Width = 1000, style = "border: none" }).Method(
FormMethod.Post).LocalDataSource(
"ReportDataset", @Model.Orders).ControlSettings(
 settings)

**Comment by ecosme8** [comment]
Hello Franco,

This is a code that I'm using right now and it works perfectly. What I do is create a class LocalReportsModel that has 2 DataTable Orders and Items. The function GetOrderItemsForOrderReport retuns a LocalReportsModel and fills the Datatable that you want, then you just return the model to the view and you use @Model.Orders which is the datatable filled with the data. Hope this works for you,

Controller:

[HttpPost]
public ActionResult OrderReport(string orderNumber)
        {
            LocalReportsModel model = OrderProvider.GetOrderItemsForOrderReport(orderNumber);

            TempData["ViewReport"] = true;

            return View(model);
        }

LocalReportsModel class:

public class LocalReportsModel
    {
        public DataTable Orders { get; set; }

        public DataTable Items { get; set; }
    }


GetOrderItemsForOrderReport Function:

public LocalReportsModel GetOrderForOrderReport(string orderNumber)
        {
            LocalReportsModel model = new LocalReportsModel();

string strSql = "SELECT O.SHIPMENT_ID, O.PURCHASE_ORDER_NUMBER, O.RELEASE_NUMBER, O.CHANGE_ORDER_SEQUENCE_NUMBER, ";
 strSql += "A.CODE_DESCRIPTION AS REFERENCE_IDENTIFICATION_QUALIFIER, O.REFERENCE_IDENTIFICATION, ";
strSql += "I.PRODUCT_SERVICE_ID_01, I.PRODUCT_SERVICE_ID_03, I.DESCRIPTION, I.NUMBER_OF_UNITS_SHIPPED, ";
strSql += "B.CODE_DESCRIPTION AS DATE_TIME_QUALIFIER, O.DATE_01, O.DATE_02 FROM dbo.ORDER_DETAIL O ";
strSql += "LEFT JOIN CODE_DESCRIPTIONS A ON O.REFERENCE_IDENTIFICATION_QUALIFIER = A.CODE ";
strSql += "LEFT JOIN CODE_DESCRIPTIONS B ON O.DATE_TIME_QUALIFIER = B.CODE ";
strSql += "INNER JOIN ITEM_DETAIL I ON O.PURCHASE_ORDER_NUMBER = I.ORDER_REF ";
strSql += "WHERE (I.ORDER_REF = @orderNumber OR @orderNumber = '') ";

var connectionString =
ConfigurationManager.ConnectionStrings["TransactionsDBEntities"].ConnectionString;
            
using (var connection = new SqlConnection(connectionString))
            {
                // GET ORDER DATATABLE
                using (var command = connection.CreateCommand())
                {
                    command.CommandText = strSql;
                    command.Parameters.Add("@orderNumber", SqlDbType.NVarChar);
                    command.Parameters["@orderNumber"].Value = orderNumber;

                    using (var adapter = new SqlDataAdapter(command))
                    {
                        var table = new DataTable();
                        adapter.Fill(table);
                        model.Orders = table;
                    }
                }
            }

            return model;
        }


And in the View:

@Html.MvcReportViewerFluent("App_Data/Reports/OrderReport.rdlc").ProcessingMode(ProcessingMode.Local).Attributes(
new { Height = 1000, Width = 1000, style = "border: none" }).Method(
FormMethod.Post).LocalDataSource(
"ReportDataset", @Model.Orders).ControlSettings(
 settings)

**Comment by morales-franco** [comment]
Excelent! It's work! Thank you very much!! 
My error was the FormMethod, I have a action Method GET in the controller but I had written FormMethod.Post.
Your example helped me a lot!
