### ISSUE TITLE
Print issue 

### ISSUE THREAD

**Issue by arageshashi** [ilich/MvcReportViewer#84]
When we are trying to print the report and suppose if there are 5 pages in report. Then It is printing only single page not all pages.

Is there any workaround to print all pages instead of single current page.

Thank you.

**Comment by ilich** [comment]
I changed report viewer to download file as PDF if users uses a non-IE browser. User can print the PDF wherever they want. I think this is the best fix since Report Viewer does not support any printing except ActiveX component in IE. The bug-fix will come with the next release.

**Comment by ilich** [comment]
I have published the package

**Comment by arageshashi** [comment]
Thank very much for the fedback...
