### ISSUE TITLE
Automatic report render

### ISSUE THREAD

**Issue by TomSimonsen** [ilich/MvcReportViewer#86]
Hi!

I try to render a ssrs report ("dashboard") with all parameters set in my index.cshtml, but I need to press "view report" to get it to run.

My index.cshtml looks like this:

@using MvcReportViewer;
@{
    ViewBag.Title = "Dashboard";
}
@{
    var pReportUrl = (string)TempData["reportUrl"];
    var pUserName = (string)TempData["userName"];
    const int pCustomerId = -1;
    const int pServiceId = -1;
    //var pFromDate = DateTime.Today.AddDays(-7);
    //var pToDate = DateTime.Today;
    var pFromDate = new DateTime(2015, 2, 2);
    var pToDate = new DateTime(2015, 2, 8);
    var settings = new ControlSettings {ShowToolBar = false};
}

@Html.MvcReportViewer(pReportUrl,
                    new { userName = pUserName, fromDate = pFromDate, toDate = pToDate, serviceId = pServiceId,CustomerId = pCustomerId },
                    new { Height = 800, Width = 1500, style = "border: none"}).ControlSettings(settings).;

If I try running the same report from the ReportServer, it renders automatic without pressing the "view report" button.

Is there anybody that could help me?

Regards
Tom S.

**Comment by ilich** [comment]
Unfortunately I am not able to recreate the issue with your code. The report renders automatically when I am using your code in my sample application. I'd recommend you to try using fluent interface and check both GET and POST methods for report's iframe rendering.

Sample code which uses POST method to pass report viewer parameters: https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewerExample/Views/Home/Post.cshtml

Please let me know if there is a bug in our HTML helper.

**Comment by TomSimonsen** [comment]
I just solved my issue by adding ShowReportBody = true to my ControlSettings.

Thanks!
