### ISSUE TITLE
The Local Report doesn't show

### ISSUE THREAD

**Issue by arrudaw** [ilich/MvcReportViewer#87]
Hello again!
I'm trying to implement im my project but always show me the message 
"Service unavailable!
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later. "

If I use the example from MVCReportViewer solution, the local report works fine.
In my project I added a new folder Reports inside App_Data as in the example.
Saved my report inside Reports.
In my view I wrote the follow code
@using MvcReportViewer;
@using Microsoft.Reporting.WebForms;

@Html.MvcReportViewerFluent("App_Data/Reports/RelConsolidado.rdlc").ProcessingMode(ProcessingMode.Local).ReportParameters(new { TodayDate = DateTime.Now }).Attributes(new { Height = 900, Width = 900, style = "border: none" })

Tried using method.post too.

The report has a parameter calls TodayDate.

What I'm doing wrong ? Can you help me ?

**Comment by ilich** [comment]
Please set MvcReportViewer.ShowErrorPage to be False in Web.config

```<add key="MvcReportViewer.ShowErrorPage" value="False" />```

It will force MvcReportViewer to show the exception instead of user-friendly HTML page. Let me know if there is an issue with the HTML helper itself.

**Comment by mkamoski** [comment]
FWIW, I changed my "MvcReportViewerErrorPage.htm" to the following and it works good for me...

**Comment by mkamoski** [comment]
<!DOCTYPE html>
	<html>
	<head>
		<title>Report Viewer Error</title>
	</head>
	<body>
		<h1>Service unavailable.</h1>
		<p>
			The server is temporarily unable to service your request, possibly due to maintenance, downtime, or capacity issues.
		</p>
		<p>
			Please try again later.
		</p>
		<script src="Scripts/url.js"></script>
		<script>
			var error = decodeURIComponent(url('?error')), errorType = decodeURIComponent(url('?errorType'));
			console.warn(errorType + ': ' + error);
			alert("errorType='" + errorType + "'" + "\n" + "\n" + "error='" + error + "'");

			this.Document.Write("<p>");
			this.Document.Write("errorType='" + errorType + "'");
			this.Document.Write("</p>");

			this.Document.Write("<p>");
			this.Document.Write("error='" + errorType + "'");
			this.Document.Write("</p>");
		</script>
	</body>
	</html>

**Comment by arrudaw** [comment]
I changed in the web.config and showed an error message about a datetime parameter that has in my report.
I used this code
.ReportParameters(new { TodayDate = DateTime.Now)
For now I changed to .ReportParameters(new { TodayDate = DateTime.Now.ToShortDateString()) and modified the parameter type on the report, now it works.

Thanks for your reply and awesome job.

**Comment by happieefeet** [comment]
Hi, How can I disable the Parameters toolbar in the ssrs report using mvc report viewer? ANy idea?
