### ISSUE TITLE
Zoom Control not showing in Chrome

### ISSUE THREAD

**Issue by jerrypalladino** [ilich/MvcReportViewer#88]
First off - great control - keep up the good work.
I found that the Zoom control and several other controls are missing from the viewer in Chrome.  I found this link (you probably already have seen it) - https://social.msdn.microsoft.com/Forums/silverlight/en-US/daa4287d-b33b-429b-83a6-452202bf33b0/ssrs-zoom-and-print-control-are-not-visible-in-ie11-firefox-and-chrome-works-in-older-versions?forum=sqlreportingservices

This goes on to say that certain functions are no longer support by the current version of the control according to MS.  Should I down grade to an earlier control version?

**Comment by ilich** [comment]
Yes, unfortunately there ale IE-only features in the Report Viewer Control. I implemented cross-browser support for Print button and fixed issues with scroll-bars. Let's hope that MS will implement all features to be cross-browser in the next version of control.

If you want to use some features from an old version of Report Viewer Control, I'd recommend you to take the source code, change reference to your version of the Report Viewer Control and rebuild. I think the rest should work out of the box.
