### ISSUE TITLE
What is needed to deploy without a username and password in the web config file?

### ISSUE THREAD

**Issue by mkamoski** [ilich/MvcReportViewer#89]
Dear Ilich -- 

Please help.

What is needed to deploy without a username and password in the web config file?

How should the viewer be configured so that it automatically runs under the current user's credentials?

Please advise.

Thanks.

-- Mark Kamoski

**Comment by mkamoski** [comment]
Also, how can one add the username/password properties dynamically at run-time (rather than storing it in the web config file)?

**Comment by ilich** [comment]
Option 1. Windows Authentication in SQL Server. This is the best option from my point of view.

Option 2. Use Web.config encryption. http://www.codeproject.com/Tips/795135/Encrypt-ConnectionString-in-Web-Config

Option 3. Store your username and password somewhere. Make sure they are populated in your model. You can provide username/password to the MvcReportViewer helper (check the documentation). This is the most unsecured option, and I would not recommend it.

**Comment by mkamoski** [comment]
Ilich -- 

What if one sets the reports to run locally?

Does the need for a username/password go away?

Please advise.

Thanks.

-- Mark Kamoski

**Comment by ilich** [comment]
You do not need username and password to use local reports, but you will have to provide database credentials anyway to access you data in the database.

Sincerely,
Ilya

**Comment by mkamoski** [comment]
Ilich -- 

Please help.

What are the basic steps for setting up my reports to run locally in my MVC app?

Do I just move the RDS files and the RDL files into my project and adjust the loading paths?

Or is there more to it?

Please advise.

FYI, it looks like I may have to rewrite my app to use the MvcReportViewer and run the reports locally.

FWIW, I am sorry to bother you with this, but you are an expert, and so even a one-sentence guess from you would help A LOT here because I really have no idea how to do it.

Thanks.

-- Mark Kamoski
