### ISSUE TITLE
How to show report after button click

### ISSUE THREAD

**Issue by arrudaw** [ilich/MvcReportViewer#91]
Ilya,
In all examples the reports appears on page load , but I need to load the report after the button click.
Is there a way to do it ?
Could you help me how to do that way?
I am learning MVC and a little lost.

Thanks in advanced.

**Comment by ilich** [comment]
It really depends on how you structure your application. You can create a model with property like IsReportReady. You can show the form in GET request and show the report on POST request (when IsReportReady is set to be true, for example). I'd recommend you to check http://www.asp.net/mvc tutorials. They are very good.
