### ISSUE TITLE
Getting Report Parameters from Report Server

### ISSUE THREAD

**Issue by code-unleashed** [ilich/MvcReportViewer#92]
Hey there,

First off, thank you for the great work you have done. 

 Is there a way to call the function: ReportViewer.ServerReport.GetParameters(); 

I would like to be able to build the parameter list and hiding the default list.

Thank you!

**Comment by ilich** [comment]
Hi,

No unfortunately you cannot do that out of the box. The HTML helper renders an iframe to an ASP.NET page hosting Report Viewer control. You can get the source code and add your logic to https://github.com/ilich/MvcReportViewer/blob/master/MvcReportViewer/MvcReportViewer.aspx.cs file
