### ISSUE TITLE
JavaScript runtime error when using multi value dropdowns in IE10

### ISSUE THREAD

**Issue by ajn4704** [ilich/MvcReportViewer#94]
When using multi-value dropdowns on a report in IE10, it produces the following error:
0x80004002 - JavaScript runtime error: No such interface supported

This causes the parameter box to not be able to expand dynamically because the div id "ctl32_ctl04_ctl03_divDropDown" contains no image to click and drag. This also causes an issue in that once you click off of the parameter box, you can no longer click the dropdown again as it doesn't open back up.

**Comment by ilich** [comment]
It seems to be Report Viewer Web Control issue. Please check this: https://social.msdn.microsoft.com/Forums/en-US/8f1bcaa6-20bb-4cf4-b6df-a61b948cce6e/error-no-such-interface-supported?forum=sqlreportingservices

Let me know if you have a work-around for the Report Viewer Web Control. I will try to implement this in the helper.

I am not able to recreate the issue in my local environment.
