### ISSUE TITLE
Reported content disappear/clears on mouse move

### ISSUE THREAD

**Issue by arulsr** [ilich/MvcReportViewer#97]
I am using MvcReportViewer 0.7.0 in my application, immediately after rendering if I move the mouse cursor esp on the export, print icon, the rendered contents goes off.

My syntax inside the view goes as below
@Html.MvcReportViewer("/Reports/Report1", new {Height = 600, Width = 1100, style="border:none"})

Could you please help me to solve the issue?

**Comment by ilich** [comment]
I have been trying to recreate the issue, but I am not able to do that. I think the issue might be related to your CSS/JavaScript. Please try to debug your styles in Firebug. I'd recommend to debug MvcReportViewer.js as well. Please let me know if there is an issue in the helper itself and the way to recreate it.
