### ISSUE TITLE
Will "MvcReportViewer.aspx" work with "jquery-1.9.1.js" or not?

### ISSUE THREAD

**Issue by mkamoski** [ilich/MvcReportViewer#98]
Dear Ilich (and all) --

Please help.

Will "MvcReportViewer.aspx" work with "jquery-1.9.1.js" or not?

Currently, inside "MvcReportViewer.aspx" the code is...

src="//code.jquery.com/jquery-1.11.0.min.js"

src="//code.jquery.com/jquery-migrate-1.2.1.min.js"

But, for those of us who (sadly) have to support IE8, the highest jQuery we can use is jquery-1.9.1 here.

And, furthermore, some of us (me at least) cannot link-out to "jquery.com" at all.

So, I suppose I could hack the "MvcReportViewer.aspx" page, and point to a local version of "jquery-1.11.0.min.js", but having 2 different versions of jQuery in the same project is not a good idea, IMHO.

Plus, with  MVC5 and RegisterBundles and the generic "get highest version of jQuery" syntax ("~/Scripts/jquery-{version}.js"), if I were to hack "MvcReportViewer.aspx" and package "jquery-1.11.0.min.js" in my app, then I suppose I would have to rename "jquery-1.11.0.min.js" to something else like "MySneakyExtraVersionOfJQuery.js" to help ensure the "bundles.Add" call does not include the wrong jQuery.

So, while I know IE8 support is my problem, (and it not necessarily your problem), and while I also believe it is not necessary for a modern app to support IE8, but still I must satisfy my customer, and so  I should ask you about this issue for your advice and suggestions, because you are the MvcReportViewer expert, etc.

What do you think?

Please advise.

Thanks.

-- Mark Kamoski

**Comment by mkamoski** [comment]
All -- 

This is a follow-up to my post above, about MvcReportViewer and jQuery, etc.

FYI, as a careful workaround to my plight describe above, I now simply downloaded the required MvcReportViewer JS and renamed the files and put the files  in my MVC5 project (a project that must support IE8 and only use "jQuery 1.9.1" here), and then I simple did the following in the "MvcReportViewer.aspx" file...

Changed from this...

``` <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>

``` <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

...to this...

``` <script type="text/javascript" src="<%=this.ResolveUrl("~/Scripts/MvcReportViewerEx1.js") %>"></script>

``` <script type="text/javascript" src="<%=this.ResolveUrl("~/Scripts/MvcReportViewerEx2.js") %>"></script>

...so that is perhaps a bit hacky  but it is clear and simple and easy and works fine for now, so I am going with it, until something better comes along.

Please let me know if there is a better way to do it, etc.

Thanks.

-- Mark Kamoski

**Comment by mkamoski** [comment]
```javascript

//Changed from this...

<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>

<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

//...to this...

<script type="text/javascript" src="<%=this.ResolveUrl("~/Scripts/MvcReportViewerEx1.js") %>"></script>

<script type="text/javascript" src="<%=this.ResolveUrl("~/Scripts/MvcReportViewerEx2.js") %>"></script>

```

(I hope I got the code block syntax right this time.)

(Wish I could edit a comment.)

**Comment by ilich** [comment]
I have reviewed out JavaScript code. You will safe downgrading the jQuery version to 1.9.1. I think you can also remove the reference to jQuery migrate if you will go this way. Please let me know if there will be some issues. I will apply a fix then.

**Comment by mkamoski** [comment]
FYI, "jQuery 1.9.1" is working fine with the MvcReportViewer for me, no problems at all.

**Comment by tiesont** [comment]
I'm not sure I follow what the issue with 1.11.x and up would be. The **2.x** version dropped support for non-compliant browsers (IE8 being the villain generally everyone hates), but **not** 1.11.x. Where you getting specific errors with 1.11.x aren't present with 1.9.x?

**Comment by mkamoski** [comment]
tiesont -- The problem that I was facing is that I personally need to support IE8. So per the jQuery site, if one wants to support IE8 and still use jQuery then the highest version of jQuery that a person can use is "jQuery 1.9.1". So, I had to make sure my project linked to "jQuery 1.9.1". But the MvcReportViewer, which my project also has, links to "jQuery 1.11 something". So I had to have 2 versions of jQuery in my project, which is not a good idea in general, especially with the MVC version-generic Bundle syntax, which grabs the highest version. So instead of faking out the standard bundling process, I instead hacked the file names of the "jQuery 1.11 something" to be non-colliding with "jQuery 1.9.1" during bundling, then I hacked the MvcReportViewer ASPX to use local-path (which I had to do anyway because I cannot link-out to non-local sites in my project). Etc. The code is above. I hope this is clear enough. Let me know if you have any other questions. Thanks. -- Mark Kamoski

**Comment by tiesont** [comment]
@mkamoski Like I mentioned: [1.11.x supports IE8](https://jquery.com/browser-support/). jQuery Migrate is needed from 1.9.x onward to continue supporting some removed features ($.browser being the one causing the most issues). Remember, if you're basing your "I need 1.9.x to support IE8" off of [this article](http://blog.jquery.com/2013/01/15/jquery-1-9-final-jquery-2-0-beta-migrate-final-released/), that post was part of the 1.9 release notes published in 2013. Every subsequent release still supports IE8.

Obviously, if what you have works, run with it; I'm just suggesting you might not need to the extra work, hence why I asked if you're seeing bugs with 1.11 that don't appear with 1.9.

**Comment by mkamoski** [comment]
@tiesont -- jQuery 1.11 did not run at all for me with IE11 EnterpriseMode=On or when in actual IE8. So maybe I needed  migrate shim? Or something? I do not know. Just looks like IE8 support in jQuery is flaky after 1.9.1 IMHO. So migrate shim or multiple jQuery versions or whatever, seems a jumble kludge to me. Anyway I am U and R now so....

**Comment by tiesont** [comment]
@mkamoski It doesn't hurt to load the [jQuery Migrate](https://github.com/jquery/jquery-migrate/) plugin/shim. It simply backfills the features that were removed from the 1.9 release and up, and logs some messages to the console to let you know what deprecated features are being used (logging can be disabled for production). It would need be loaded after jQuery but before any other plugins.

It's also worth noting that the emulator in IE11 doesn't faithfully reproduce the behavior of an actual IE8 instance, so you might want to try running one of the virtual machines from [modern.ie](http://dev.modern.ie/tools/vms/) if you haven't already.

**Comment by mkamoski** [comment]
BTW, I just went to....  http://jquery.com/download/  ....for another project and another reason... and I came across this...  "jQuery 2.x has the same API as jQuery 1.x, but does not support Internet Explorer 6, 7, or 8... Since IE 8 is still relatively common, we recommend using the 1.x version unless you are certain no IE 6/7/8 users are visiting the site"  ....so FWIW that's what the jQuery folks are currently saying.

**Comment by tiesont** [comment]
Yes. There are (currently) two **branches** of jQuery. The 2.x branch drops browser sniffing in favor of feature detection. The 1.x branch still attempts to work around older IE/Trident bugs, with the Migrate plugin being needed mostly to backfill removed functions like `$.browser`.

So, any version that starts with a **1** still supports IE8. You **can** use 1.9.x if you want, or you can use 1.10, 1.11, 1.12, etc. if that's what NuGet is installing in the MVC template.

As I keep asking:
 -- Where you getting specific errors with 1.11.x that aren't present with 1.9.x?

The point I've tried to make is that you *shouldn't* have to use an older version of jQuery than what this project references. I also note:
 -- if what you have works, run with it.

So, if you have a workable solution, awesome.
